// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

public interface AccountInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.gateway.AccountInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string account = 1;</code>
   */
  String getAccount();
  /**
   * <code>optional string account = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();
}
