// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_type_def.proto

package com.demo.model.proto.gateway;

/**
 * <pre>
 * 客户交易状态 
 * </pre>
 *
 * Protobuf enum {@code com.demo.model.proto.gateway.AccountRightType}
 */
public enum AccountRightType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 未知权限
   * </pre>
   *
   * <code>UNKNOWN_RIGHT = 0;</code>
   */
  UNKNOWN_RIGHT(0),
  /**
   * <pre>
   * 正常交易状态 
   * </pre>
   *
   * <code>ACC_RIGHT_NORMAL = 1;</code>
   */
  ACC_RIGHT_NORMAL(1),
  /**
   * <pre>
   * 禁止交易
   * </pre>
   *
   * <code>ACC_RIGHT_NOTRADE = 2;</code>
   */
  ACC_RIGHT_NOTRADE(2),
  /**
   * <pre>
   * 只可平仓
   * </pre>
   *
   * <code>ACC_RIGHT_CLOSE = 3;</code>
   */
  ACC_RIGHT_CLOSE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 未知权限
   * </pre>
   *
   * <code>UNKNOWN_RIGHT = 0;</code>
   */
  public static final int UNKNOWN_RIGHT_VALUE = 0;
  /**
   * <pre>
   * 正常交易状态 
   * </pre>
   *
   * <code>ACC_RIGHT_NORMAL = 1;</code>
   */
  public static final int ACC_RIGHT_NORMAL_VALUE = 1;
  /**
   * <pre>
   * 禁止交易
   * </pre>
   *
   * <code>ACC_RIGHT_NOTRADE = 2;</code>
   */
  public static final int ACC_RIGHT_NOTRADE_VALUE = 2;
  /**
   * <pre>
   * 只可平仓
   * </pre>
   *
   * <code>ACC_RIGHT_CLOSE = 3;</code>
   */
  public static final int ACC_RIGHT_CLOSE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static AccountRightType valueOf(int value) {
    return forNumber(value);
  }

  public static AccountRightType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_RIGHT;
      case 1: return ACC_RIGHT_NORMAL;
      case 2: return ACC_RIGHT_NOTRADE;
      case 3: return ACC_RIGHT_CLOSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AccountRightType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AccountRightType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AccountRightType>() {
          public AccountRightType findValueByNumber(int number) {
            return AccountRightType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return TradeTypeDef.getDescriptor()
        .getEnumTypes().get(23);
  }

  private static final AccountRightType[] VALUES = values();

  public static AccountRightType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AccountRightType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.demo.model.proto.gateway.AccountRightType)
}

