// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

public interface FutureBalanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.gateway.FutureBalance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 投资者账户
   * </pre>
   *
   * <code>optional string account = 1;</code>
   */
  String getAccount();
  /**
   * <pre>
   * 投资者账户
   * </pre>
   *
   * <code>optional string account = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <pre>
   * 投资者名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  String getName();
  /**
   * <pre>
   * 投资者名称
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 精度
   * </pre>
   *
   * <code>optional uint32 precision = 3;</code>
   */
  int getPrecision();

  /**
   * <pre>
   * 币种
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CurrencyType currency = 4;</code>
   */
  int getCurrencyValue();
  /**
   * <pre>
   * 币种
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CurrencyType currency = 4;</code>
   */
  com.demo.model.proto.trade.common.CurrencyType getCurrency();

  /**
   * <pre>
   * 昨结
   * </pre>
   *
   * <code>optional int64 pre_balance = 5;</code>
   */
  long getPreBalance();

  /**
   * <pre>
   * 上日未到期平盈
   * </pre>
   *
   * <code>optional int64 pre_unexp_profit = 6;</code>
   */
  long getPreUnexpProfit();

  /**
   * <pre>
   * 上日LME持仓平盈
   * </pre>
   *
   * <code>optional int64 pre_lme_position_profit = 7;</code>
   */
  long getPreLmePositionProfit();

  /**
   * <pre>
   * 上日权益
   * </pre>
   *
   * <code>optional int64 pre_equity = 8;</code>
   */
  long getPreEquity();

  /**
   * <pre>
   * 昨可用
   * </pre>
   *
   * <code>optional int64 pre_available = 9;</code>
   */
  long getPreAvailable();

  /**
   * <pre>
   * 上日市值权益(动态盈亏)
   * </pre>
   *
   * <code>optional int64 pre_maket_equity = 10;</code>
   */
  long getPreMaketEquity();

  /**
   * <pre>
   * 可用
   * </pre>
   *
   * <code>optional int64 available = 11;</code>
   */
  long getAvailable();

  /**
   * <pre>
   * 可取
   * </pre>
   *
   * <code>optional int64 with_draw = 12;</code>
   */
  long getWithDraw();

  /**
   * <pre>
   * 资金调整
   * </pre>
   *
   * <code>optional int64 adjust_value = 13;</code>
   */
  long getAdjustValue();

  /**
   * <pre>
   * 质押资金
   * </pre>
   *
   * <code>optional int64 pledged = 14;</code>
   */
  long getPledged();

  /**
   * <pre>
   * 手续费
   * </pre>
   *
   * <code>optional int64 commission = 15;</code>
   */
  long getCommission();

  /**
   * <pre>
   * 交易费
   * </pre>
   *
   * <code>optional int64 fee = 16;</code>
   */
  long getFee();

  /**
   * <pre>
   * 客户手续费
   * </pre>
   *
   * <code>optional int64 account_fee = 17;</code>
   */
  long getAccountFee();

  /**
   * <pre>
   * 买入冻结
   * </pre>
   *
   * <code>optional int64 buy_freeze = 18;</code>
   */
  long getBuyFreeze();

  /**
   * <pre>
   * 冻结保证金
   * </pre>
   *
   * <code>optional int64 buy_freeze_margin = 19;</code>
   */
  long getBuyFreezeMargin();

  /**
   * <pre>
   * 冻结费用
   * </pre>
   *
   * <code>optional int64 freeze_fee = 20;</code>
   */
  long getFreezeFee();

  /**
   * <pre>
   * 卖出冻结
   * </pre>
   *
   * <code>optional int64 sell_freeze = 21;</code>
   */
  long getSellFreeze();

  /**
   * <pre>
   * 卖出冻结保证金
   * </pre>
   *
   * <code>optional int64 sell_freeze_margin = 22;</code>
   */
  long getSellFreezeMargin();

  /**
   * <pre>
   * 平仓盈亏
   * </pre>
   *
   * <code>optional int64 close_profit = 23;</code>
   */
  long getCloseProfit();

  /**
   * <pre>
   * 未到期平盈
   * </pre>
   *
   * <code>optional int64 unexp_profit = 24;</code>
   */
  long getUnexpProfit();

  /**
   * <pre>
   * 到期平仓盈亏
   * </pre>
   *
   * <code>optional int64 exp_profit = 25;</code>
   */
  long getExpProfit();

  /**
   * <pre>
   * 不含LME持仓盈亏
   * </pre>
   *
   * <code>optional int64 position_profit = 26;</code>
   */
  long getPositionProfit();

  /**
   * <pre>
   * LME持仓盈亏
   * </pre>
   *
   * <code>optional int64 lme_position_profit = 27;</code>
   */
  long getLmePositionProfit();

  /**
   * <pre>
   * 初始保证金
   * </pre>
   *
   * <code>optional int64 initial_margin = 28;</code>
   */
  long getInitialMargin();

  /**
   * <pre>
   * 维持保证金
   * </pre>
   *
   * <code>optional int64 maintenance_margin = 29;</code>
   */
  long getMaintenanceMargin();

  /**
   * <pre>
   * 上手初始保证金
   * </pre>
   *
   * <code>optional int64 upper_inital_margin = 30;</code>
   */
  long getUpperInitalMargin();

  /**
   * <pre>
   * 上手维持保证金
   * </pre>
   *
   * <code>optional int64 upper_maintenance_margin = 31;</code>
   */
  long getUpperMaintenanceMargin();

  /**
   * <pre>
   * LME贴现
   * </pre>
   *
   * <code>optional int64 discount = 32;</code>
   */
  long getDiscount();

  /**
   * <pre>
   * 入金
   * </pre>
   *
   * <code>optional int64 deposit = 33;</code>
   */
  long getDeposit();

  /**
   * <pre>
   * 出金
   * </pre>
   *
   * <code>optional int64 drawing = 34;</code>
   */
  long getDrawing();

  /**
   * <pre>
   * 汇入资金
   * </pre>
   *
   * <code>optional int64 swap_in_value = 35;</code>
   */
  long getSwapInValue();

  /**
   * <pre>
   * 汇出资金
   * </pre>
   *
   * <code>optional int64 swap_out_value = 36;</code>
   */
  long getSwapOutValue();

  /**
   * <pre>
   * 权利金收取
   * </pre>
   *
   * <code>optional int64 premium_income = 37;</code>
   */
  long getPremiumIncome();

  /**
   * <pre>
   * 权利金支付
   * </pre>
   *
   * <code>optional int64 premium_pay = 38;</code>
   */
  long getPremiumPay();

  /**
   * <pre>
   * 结存
   * </pre>
   *
   * <code>optional int64 balance = 39;</code>
   */
  long getBalance();

  /**
   * <pre>
   * 当日权益
   * </pre>
   *
   * <code>optional int64 equity = 40;</code>
   */
  long getEquity();

  /**
   * <pre>
   * 市值
   * </pre>
   *
   * <code>optional int64 market_equity = 41;</code>
   */
  long getMarketEquity();

  /**
   * <pre>
   * 授信资金
   * </pre>
   *
   * <code>optional int64 auth_value = 42;</code>
   */
  long getAuthValue();

  /**
   * <pre>
   *汇率
   * </pre>
   *
   * <code>optional int64 exchange_rate = 43;</code>
   */
  long getExchangeRate();
}
