// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

public interface QueryPositionReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.gateway.QueryPositionReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>optional uint64 session_id = 1;</code>
   */
  long getSessionId();

  /**
   * <code>optional string account = 2;</code>
   */
  String getAccount();
  /**
   * <code>optional string account = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
   */
  int getExchangeValue();
  /**
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
   */
  com.demo.model.proto.trade.common.ExchangeType getExchange();

  /**
   * <code>optional string instr_code = 4;</code>
   */
  String getInstrCode();
  /**
   * <code>optional string instr_code = 4;</code>
   */
  com.google.protobuf.ByteString
      getInstrCodeBytes();

  /**
   * <pre>
   * 页码
   * </pre>
   *
   * <code>optional uint32 page_num = 5;</code>
   */
  int getPageNum();

  /**
   * <pre>
   * 请求行数
   * </pre>
   *
   * <code>optional uint32 request_num = 6;</code>
   */
  int getRequestNum();
}
