// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

/**
 * <pre>
 * 查询账户保证金计算
 * </pre>
 *
 * Protobuf type {@code com.demo.model.proto.gateway.QueryAccountMarginRentReq}
 */
public  final class QueryAccountMarginRentReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.demo.model.proto.gateway.QueryAccountMarginRentReq)
    QueryAccountMarginRentReqOrBuilder {
  // Use QueryAccountMarginRentReq.newBuilder() to construct.
  private QueryAccountMarginRentReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryAccountMarginRentReq() {
    sessionId_ = 0L;
    account_ = "";
    exchange_ = 0;
    productCode_ = "";
    category_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private QueryAccountMarginRentReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            sessionId_ = input.readUInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            account_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            exchange_ = rawValue;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            productCode_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            category_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            QueryAccountMarginRentReq.class, Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private long sessionId_;
  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>optional uint64 session_id = 1;</code>
   */
  public long getSessionId() {
    return sessionId_;
  }

  public static final int ACCOUNT_FIELD_NUMBER = 2;
  private volatile Object account_;
  /**
   * <pre>
   * 账户
   * </pre>
   *
   * <code>optional string account = 2;</code>
   */
  public String getAccount() {
    Object ref = account_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      account_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 账户
   * </pre>
   *
   * <code>optional string account = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAccountBytes() {
    Object ref = account_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      account_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCHANGE_FIELD_NUMBER = 3;
  private int exchange_;
  /**
   * <pre>
   * 交易所
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
   */
  public int getExchangeValue() {
    return exchange_;
  }
  /**
   * <pre>
   * 交易所
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
   */
  public com.demo.model.proto.trade.common.ExchangeType getExchange() {
    com.demo.model.proto.trade.common.ExchangeType result = com.demo.model.proto.trade.common.ExchangeType.valueOf(exchange_);
    return result == null ? com.demo.model.proto.trade.common.ExchangeType.UNRECOGNIZED : result;
  }

  public static final int PRODUCT_CODE_FIELD_NUMBER = 4;
  private volatile Object productCode_;
  /**
   * <pre>
   * 品种代码
   * </pre>
   *
   * <code>optional string product_code = 4;</code>
   */
  public String getProductCode() {
    Object ref = productCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      productCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 品种代码
   * </pre>
   *
   * <code>optional string product_code = 4;</code>
   */
  public com.google.protobuf.ByteString
      getProductCodeBytes() {
    Object ref = productCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      productCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 6;
  private int category_;
  /**
   * <pre>
   * 合约大类
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
   */
  public int getCategoryValue() {
    return category_;
  }
  /**
   * <pre>
   * 合约大类
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
   */
  public com.demo.model.proto.trade.common.CategoryType getCategory() {
    com.demo.model.proto.trade.common.CategoryType result = com.demo.model.proto.trade.common.CategoryType.valueOf(category_);
    return result == null ? com.demo.model.proto.trade.common.CategoryType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sessionId_ != 0L) {
      output.writeUInt64(1, sessionId_);
    }
    if (!getAccountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, account_);
    }
    if (exchange_ != com.demo.model.proto.trade.common.ExchangeType.UNKNOWN.getNumber()) {
      output.writeEnum(3, exchange_);
    }
    if (!getProductCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, productCode_);
    }
    if (category_ != com.demo.model.proto.trade.common.CategoryType.UNKNOWN_NONE.getNumber()) {
      output.writeEnum(6, category_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, sessionId_);
    }
    if (!getAccountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, account_);
    }
    if (exchange_ != com.demo.model.proto.trade.common.ExchangeType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, exchange_);
    }
    if (!getProductCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, productCode_);
    }
    if (category_ != com.demo.model.proto.trade.common.CategoryType.UNKNOWN_NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, category_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof QueryAccountMarginRentReq)) {
      return super.equals(obj);
    }
    QueryAccountMarginRentReq other = (QueryAccountMarginRentReq) obj;

    boolean result = true;
    result = result && (getSessionId()
        == other.getSessionId());
    result = result && getAccount()
        .equals(other.getAccount());
    result = result && exchange_ == other.exchange_;
    result = result && getProductCode()
        .equals(other.getProductCode());
    result = result && category_ == other.category_;
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAccount().hashCode();
    hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
    hash = (53 * hash) + exchange_;
    hash = (37 * hash) + PRODUCT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getProductCode().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + category_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static QueryAccountMarginRentReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryAccountMarginRentReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryAccountMarginRentReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryAccountMarginRentReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryAccountMarginRentReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryAccountMarginRentReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryAccountMarginRentReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static QueryAccountMarginRentReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryAccountMarginRentReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryAccountMarginRentReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueryAccountMarginRentReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查询账户保证金计算
   * </pre>
   *
   * Protobuf type {@code com.demo.model.proto.gateway.QueryAccountMarginRentReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.demo.model.proto.gateway.QueryAccountMarginRentReq)
      QueryAccountMarginRentReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryAccountMarginRentReq.class, Builder.class);
    }

    // Construct using com.demo.model.proto.gateway.QueryAccountMarginRentReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      sessionId_ = 0L;

      account_ = "";

      exchange_ = 0;

      productCode_ = "";

      category_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_descriptor;
    }

    public QueryAccountMarginRentReq getDefaultInstanceForType() {
      return QueryAccountMarginRentReq.getDefaultInstance();
    }

    public QueryAccountMarginRentReq build() {
      QueryAccountMarginRentReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public QueryAccountMarginRentReq buildPartial() {
      QueryAccountMarginRentReq result = new QueryAccountMarginRentReq(this);
      result.sessionId_ = sessionId_;
      result.account_ = account_;
      result.exchange_ = exchange_;
      result.productCode_ = productCode_;
      result.category_ = category_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof QueryAccountMarginRentReq) {
        return mergeFrom((QueryAccountMarginRentReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(QueryAccountMarginRentReq other) {
      if (other == QueryAccountMarginRentReq.getDefaultInstance()) return this;
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (!other.getAccount().isEmpty()) {
        account_ = other.account_;
        onChanged();
      }
      if (other.exchange_ != 0) {
        setExchangeValue(other.getExchangeValue());
      }
      if (!other.getProductCode().isEmpty()) {
        productCode_ = other.productCode_;
        onChanged();
      }
      if (other.category_ != 0) {
        setCategoryValue(other.getCategoryValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      QueryAccountMarginRentReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (QueryAccountMarginRentReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long sessionId_ ;
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>optional uint64 session_id = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>optional uint64 session_id = 1;</code>
     */
    public Builder setSessionId(long value) {
      
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>optional uint64 session_id = 1;</code>
     */
    public Builder clearSessionId() {
      
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private Object account_ = "";
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public String getAccount() {
      Object ref = account_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        account_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public Builder setAccount(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      account_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public Builder clearAccount() {
      
      account_ = getDefaultInstance().getAccount();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public Builder setAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      account_ = value;
      onChanged();
      return this;
    }

    private int exchange_ = 0;
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public int getExchangeValue() {
      return exchange_;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public Builder setExchangeValue(int value) {
      exchange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public com.demo.model.proto.trade.common.ExchangeType getExchange() {
      com.demo.model.proto.trade.common.ExchangeType result = com.demo.model.proto.trade.common.ExchangeType.valueOf(exchange_);
      return result == null ? com.demo.model.proto.trade.common.ExchangeType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public Builder setExchange(com.demo.model.proto.trade.common.ExchangeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      exchange_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public Builder clearExchange() {
      
      exchange_ = 0;
      onChanged();
      return this;
    }

    private Object productCode_ = "";
    /**
     * <pre>
     * 品种代码
     * </pre>
     *
     * <code>optional string product_code = 4;</code>
     */
    public String getProductCode() {
      Object ref = productCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        productCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 品种代码
     * </pre>
     *
     * <code>optional string product_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProductCodeBytes() {
      Object ref = productCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        productCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 品种代码
     * </pre>
     *
     * <code>optional string product_code = 4;</code>
     */
    public Builder setProductCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 品种代码
     * </pre>
     *
     * <code>optional string product_code = 4;</code>
     */
    public Builder clearProductCode() {
      
      productCode_ = getDefaultInstance().getProductCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 品种代码
     * </pre>
     *
     * <code>optional string product_code = 4;</code>
     */
    public Builder setProductCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productCode_ = value;
      onChanged();
      return this;
    }

    private int category_ = 0;
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public int getCategoryValue() {
      return category_;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public Builder setCategoryValue(int value) {
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public com.demo.model.proto.trade.common.CategoryType getCategory() {
      com.demo.model.proto.trade.common.CategoryType result = com.demo.model.proto.trade.common.CategoryType.valueOf(category_);
      return result == null ? com.demo.model.proto.trade.common.CategoryType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public Builder setCategory(com.demo.model.proto.trade.common.CategoryType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      category_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public Builder clearCategory() {
      
      category_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.demo.model.proto.gateway.QueryAccountMarginRentReq)
  }

  // @@protoc_insertion_point(class_scope:com.demo.model.proto.gateway.QueryAccountMarginRentReq)
  private static final QueryAccountMarginRentReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueryAccountMarginRentReq();
  }

  public static QueryAccountMarginRentReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryAccountMarginRentReq>
      PARSER = new com.google.protobuf.AbstractParser<QueryAccountMarginRentReq>() {
    public QueryAccountMarginRentReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryAccountMarginRentReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryAccountMarginRentReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QueryAccountMarginRentReq> getParserForType() {
    return PARSER;
  }

  public QueryAccountMarginRentReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

