// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

/**
 * <pre>
 * 查询当日委托
 * </pre>
 *
 * Protobuf type {@code com.demo.model.proto.gateway.QueryOrderReq}
 */
public  final class QueryOrderReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.demo.model.proto.gateway.QueryOrderReq)
    QueryOrderReqOrBuilder {
  // Use QueryOrderReq.newBuilder() to construct.
  private QueryOrderReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryOrderReq() {
    sessionId_ = 0L;
    account_ = "";
    exchange_ = 0;
    instrCode_ = "";
    direct_ = 0;
    category_ = 0;
    product_ = 0;
    orderType_ = 0;
    timeInForce_ = 0;
    hedge_ = 0;
    reqId_ = "";
    exchangeOrderId_ = "";
    serverFlag_ = "";
    expireTime_ = "";
    isRisk_ = false;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private QueryOrderReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            sessionId_ = input.readUInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            account_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            exchange_ = rawValue;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            instrCode_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            direct_ = rawValue;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            category_ = rawValue;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            product_ = rawValue;
            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            orderType_ = rawValue;
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            timeInForce_ = rawValue;
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            hedge_ = rawValue;
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            reqId_ = s;
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            exchangeOrderId_ = s;
            break;
          }
          case 106: {
            String s = input.readStringRequireUtf8();

            serverFlag_ = s;
            break;
          }
          case 114: {
            String s = input.readStringRequireUtf8();

            expireTime_ = s;
            break;
          }
          case 120: {

            isRisk_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryOrderReq_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryOrderReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            QueryOrderReq.class, Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private long sessionId_;
  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>optional uint64 session_id = 1;</code>
   */
  public long getSessionId() {
    return sessionId_;
  }

  public static final int ACCOUNT_FIELD_NUMBER = 2;
  private volatile Object account_;
  /**
   * <pre>
   * 账户
   * </pre>
   *
   * <code>optional string account = 2;</code>
   */
  public String getAccount() {
    Object ref = account_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      account_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 账户
   * </pre>
   *
   * <code>optional string account = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAccountBytes() {
    Object ref = account_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      account_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCHANGE_FIELD_NUMBER = 3;
  private int exchange_;
  /**
   * <pre>
   * 交易所
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
   */
  public int getExchangeValue() {
    return exchange_;
  }
  /**
   * <pre>
   * 交易所
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
   */
  public com.demo.model.proto.trade.common.ExchangeType getExchange() {
    com.demo.model.proto.trade.common.ExchangeType result = com.demo.model.proto.trade.common.ExchangeType.valueOf(exchange_);
    return result == null ? com.demo.model.proto.trade.common.ExchangeType.UNRECOGNIZED : result;
  }

  public static final int INSTR_CODE_FIELD_NUMBER = 4;
  private volatile Object instrCode_;
  /**
   * <pre>
   * 合约代码
   * </pre>
   *
   * <code>optional string instr_code = 4;</code>
   */
  public String getInstrCode() {
    Object ref = instrCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      instrCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 合约代码
   * </pre>
   *
   * <code>optional string instr_code = 4;</code>
   */
  public com.google.protobuf.ByteString
      getInstrCodeBytes() {
    Object ref = instrCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      instrCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECT_FIELD_NUMBER = 5;
  private int direct_;
  /**
   * <pre>
   * 买卖方向
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.BSDirectType direct = 5;</code>
   */
  public int getDirectValue() {
    return direct_;
  }
  /**
   * <pre>
   * 买卖方向
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.BSDirectType direct = 5;</code>
   */
  public BSDirectType getDirect() {
    BSDirectType result = BSDirectType.valueOf(direct_);
    return result == null ? BSDirectType.UNRECOGNIZED : result;
  }

  public static final int CATEGORY_FIELD_NUMBER = 6;
  private int category_;
  /**
   * <pre>
   * 合约大类
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
   */
  public int getCategoryValue() {
    return category_;
  }
  /**
   * <pre>
   * 合约大类
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
   */
  public com.demo.model.proto.trade.common.CategoryType getCategory() {
    com.demo.model.proto.trade.common.CategoryType result = com.demo.model.proto.trade.common.CategoryType.valueOf(category_);
    return result == null ? com.demo.model.proto.trade.common.CategoryType.UNRECOGNIZED : result;
  }

  public static final int PRODUCT_FIELD_NUMBER = 7;
  private int product_;
  /**
   * <pre>
   * 品种类型 
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ProductType product = 7;</code>
   */
  public int getProductValue() {
    return product_;
  }
  /**
   * <pre>
   * 品种类型 
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ProductType product = 7;</code>
   */
  public com.demo.model.proto.trade.common.ProductType getProduct() {
    com.demo.model.proto.trade.common.ProductType result = com.demo.model.proto.trade.common.ProductType.valueOf(product_);
    return result == null ? com.demo.model.proto.trade.common.ProductType.UNRECOGNIZED : result;
  }

  public static final int ORDER_TYPE_FIELD_NUMBER = 8;
  private int orderType_;
  /**
   * <pre>
   * 委托类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.OrderTypeType order_type = 8;</code>
   */
  public int getOrderTypeValue() {
    return orderType_;
  }
  /**
   * <pre>
   * 委托类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.OrderTypeType order_type = 8;</code>
   */
  public OrderTypeType getOrderType() {
    OrderTypeType result = OrderTypeType.valueOf(orderType_);
    return result == null ? OrderTypeType.UNRECOGNIZED : result;
  }

  public static final int TIME_IN_FORCE_FIELD_NUMBER = 9;
  private int timeInForce_;
  /**
   * <pre>
   * 委托有效类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.TimeInForceType time_in_force = 9;</code>
   */
  public int getTimeInForceValue() {
    return timeInForce_;
  }
  /**
   * <pre>
   * 委托有效类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.TimeInForceType time_in_force = 9;</code>
   */
  public TimeInForceType getTimeInForce() {
    TimeInForceType result = TimeInForceType.valueOf(timeInForce_);
    return result == null ? TimeInForceType.UNRECOGNIZED : result;
  }

  public static final int HEDGE_FIELD_NUMBER = 10;
  private int hedge_;
  /**
   * <pre>
   * 投保标志
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.HedgeFlagType hedge = 10;</code>
   */
  public int getHedgeValue() {
    return hedge_;
  }
  /**
   * <pre>
   * 投保标志
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.HedgeFlagType hedge = 10;</code>
   */
  public HedgeFlagType getHedge() {
    HedgeFlagType result = HedgeFlagType.valueOf(hedge_);
    return result == null ? HedgeFlagType.UNRECOGNIZED : result;
  }

  public static final int REQ_ID_FIELD_NUMBER = 11;
  private volatile Object reqId_;
  /**
   * <pre>
   * 请求ID 
   * </pre>
   *
   * <code>optional string req_id = 11;</code>
   */
  public String getReqId() {
    Object ref = reqId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      reqId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 请求ID 
   * </pre>
   *
   * <code>optional string req_id = 11;</code>
   */
  public com.google.protobuf.ByteString
      getReqIdBytes() {
    Object ref = reqId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      reqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCHANGE_ORDER_ID_FIELD_NUMBER = 12;
  private volatile Object exchangeOrderId_;
  /**
   * <pre>
   * 交易所委托序号
   * </pre>
   *
   * <code>optional string exchange_order_id = 12;</code>
   */
  public String getExchangeOrderId() {
    Object ref = exchangeOrderId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      exchangeOrderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 交易所委托序号
   * </pre>
   *
   * <code>optional string exchange_order_id = 12;</code>
   */
  public com.google.protobuf.ByteString
      getExchangeOrderIdBytes() {
    Object ref = exchangeOrderId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      exchangeOrderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVER_FLAG_FIELD_NUMBER = 13;
  private volatile Object serverFlag_;
  /**
   * <pre>
   * 服务器标识(易盛接口使用)
   * </pre>
   *
   * <code>optional string server_flag = 13;</code>
   */
  public String getServerFlag() {
    Object ref = serverFlag_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serverFlag_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 服务器标识(易盛接口使用)
   * </pre>
   *
   * <code>optional string server_flag = 13;</code>
   */
  public com.google.protobuf.ByteString
      getServerFlagBytes() {
    Object ref = serverFlag_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serverFlag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRE_TIME_FIELD_NUMBER = 14;
  private volatile Object expireTime_;
  /**
   * <pre>
   * 委托过期时间(GTD)时需要 日期时间戳
   * </pre>
   *
   * <code>optional string expire_time = 14;</code>
   */
  public String getExpireTime() {
    Object ref = expireTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      expireTime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 委托过期时间(GTD)时需要 日期时间戳
   * </pre>
   *
   * <code>optional string expire_time = 14;</code>
   */
  public com.google.protobuf.ByteString
      getExpireTimeBytes() {
    Object ref = expireTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      expireTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_RISK_FIELD_NUMBER = 15;
  private boolean isRisk_;
  /**
   * <pre>
   * 是否是风险单
   * </pre>
   *
   * <code>optional bool is_risk = 15;</code>
   */
  public boolean getIsRisk() {
    return isRisk_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sessionId_ != 0L) {
      output.writeUInt64(1, sessionId_);
    }
    if (!getAccountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, account_);
    }
    if (exchange_ != com.demo.model.proto.trade.common.ExchangeType.UNKNOWN.getNumber()) {
      output.writeEnum(3, exchange_);
    }
    if (!getInstrCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, instrCode_);
    }
    if (direct_ != BSDirectType.UNKNOWN_BS.getNumber()) {
      output.writeEnum(5, direct_);
    }
    if (category_ != com.demo.model.proto.trade.common.CategoryType.UNKNOWN_NONE.getNumber()) {
      output.writeEnum(6, category_);
    }
    if (product_ != com.demo.model.proto.trade.common.ProductType.UNKNOWN_PRODUCT.getNumber()) {
      output.writeEnum(7, product_);
    }
    if (orderType_ != OrderTypeType.UNKNOWN_ORDER_STATUS.getNumber()) {
      output.writeEnum(8, orderType_);
    }
    if (timeInForce_ != TimeInForceType.GFD.getNumber()) {
      output.writeEnum(9, timeInForce_);
    }
    if (hedge_ != HedgeFlagType.UNKNOWN_HEDGE.getNumber()) {
      output.writeEnum(10, hedge_);
    }
    if (!getReqIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, reqId_);
    }
    if (!getExchangeOrderIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, exchangeOrderId_);
    }
    if (!getServerFlagBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, serverFlag_);
    }
    if (!getExpireTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, expireTime_);
    }
    if (isRisk_ != false) {
      output.writeBool(15, isRisk_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, sessionId_);
    }
    if (!getAccountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, account_);
    }
    if (exchange_ != com.demo.model.proto.trade.common.ExchangeType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, exchange_);
    }
    if (!getInstrCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, instrCode_);
    }
    if (direct_ != BSDirectType.UNKNOWN_BS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, direct_);
    }
    if (category_ != com.demo.model.proto.trade.common.CategoryType.UNKNOWN_NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, category_);
    }
    if (product_ != com.demo.model.proto.trade.common.ProductType.UNKNOWN_PRODUCT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, product_);
    }
    if (orderType_ != OrderTypeType.UNKNOWN_ORDER_STATUS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, orderType_);
    }
    if (timeInForce_ != TimeInForceType.GFD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, timeInForce_);
    }
    if (hedge_ != HedgeFlagType.UNKNOWN_HEDGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, hedge_);
    }
    if (!getReqIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, reqId_);
    }
    if (!getExchangeOrderIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, exchangeOrderId_);
    }
    if (!getServerFlagBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, serverFlag_);
    }
    if (!getExpireTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, expireTime_);
    }
    if (isRisk_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(15, isRisk_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof QueryOrderReq)) {
      return super.equals(obj);
    }
    QueryOrderReq other = (QueryOrderReq) obj;

    boolean result = true;
    result = result && (getSessionId()
        == other.getSessionId());
    result = result && getAccount()
        .equals(other.getAccount());
    result = result && exchange_ == other.exchange_;
    result = result && getInstrCode()
        .equals(other.getInstrCode());
    result = result && direct_ == other.direct_;
    result = result && category_ == other.category_;
    result = result && product_ == other.product_;
    result = result && orderType_ == other.orderType_;
    result = result && timeInForce_ == other.timeInForce_;
    result = result && hedge_ == other.hedge_;
    result = result && getReqId()
        .equals(other.getReqId());
    result = result && getExchangeOrderId()
        .equals(other.getExchangeOrderId());
    result = result && getServerFlag()
        .equals(other.getServerFlag());
    result = result && getExpireTime()
        .equals(other.getExpireTime());
    result = result && (getIsRisk()
        == other.getIsRisk());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAccount().hashCode();
    hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
    hash = (53 * hash) + exchange_;
    hash = (37 * hash) + INSTR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getInstrCode().hashCode();
    hash = (37 * hash) + DIRECT_FIELD_NUMBER;
    hash = (53 * hash) + direct_;
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + category_;
    hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
    hash = (53 * hash) + product_;
    hash = (37 * hash) + ORDER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + orderType_;
    hash = (37 * hash) + TIME_IN_FORCE_FIELD_NUMBER;
    hash = (53 * hash) + timeInForce_;
    hash = (37 * hash) + HEDGE_FIELD_NUMBER;
    hash = (53 * hash) + hedge_;
    hash = (37 * hash) + REQ_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReqId().hashCode();
    hash = (37 * hash) + EXCHANGE_ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExchangeOrderId().hashCode();
    hash = (37 * hash) + SERVER_FLAG_FIELD_NUMBER;
    hash = (53 * hash) + getServerFlag().hashCode();
    hash = (37 * hash) + EXPIRE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getExpireTime().hashCode();
    hash = (37 * hash) + IS_RISK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsRisk());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static QueryOrderReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryOrderReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryOrderReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static QueryOrderReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static QueryOrderReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryOrderReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryOrderReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static QueryOrderReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static QueryOrderReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static QueryOrderReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueryOrderReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 查询当日委托
   * </pre>
   *
   * Protobuf type {@code com.demo.model.proto.gateway.QueryOrderReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.demo.model.proto.gateway.QueryOrderReq)
      QueryOrderReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryOrderReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryOrderReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryOrderReq.class, Builder.class);
    }

    // Construct using com.demo.model.proto.gateway.QueryOrderReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      sessionId_ = 0L;

      account_ = "";

      exchange_ = 0;

      instrCode_ = "";

      direct_ = 0;

      category_ = 0;

      product_ = 0;

      orderType_ = 0;

      timeInForce_ = 0;

      hedge_ = 0;

      reqId_ = "";

      exchangeOrderId_ = "";

      serverFlag_ = "";

      expireTime_ = "";

      isRisk_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_QueryOrderReq_descriptor;
    }

    public QueryOrderReq getDefaultInstanceForType() {
      return QueryOrderReq.getDefaultInstance();
    }

    public QueryOrderReq build() {
      QueryOrderReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public QueryOrderReq buildPartial() {
      QueryOrderReq result = new QueryOrderReq(this);
      result.sessionId_ = sessionId_;
      result.account_ = account_;
      result.exchange_ = exchange_;
      result.instrCode_ = instrCode_;
      result.direct_ = direct_;
      result.category_ = category_;
      result.product_ = product_;
      result.orderType_ = orderType_;
      result.timeInForce_ = timeInForce_;
      result.hedge_ = hedge_;
      result.reqId_ = reqId_;
      result.exchangeOrderId_ = exchangeOrderId_;
      result.serverFlag_ = serverFlag_;
      result.expireTime_ = expireTime_;
      result.isRisk_ = isRisk_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof QueryOrderReq) {
        return mergeFrom((QueryOrderReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(QueryOrderReq other) {
      if (other == QueryOrderReq.getDefaultInstance()) return this;
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (!other.getAccount().isEmpty()) {
        account_ = other.account_;
        onChanged();
      }
      if (other.exchange_ != 0) {
        setExchangeValue(other.getExchangeValue());
      }
      if (!other.getInstrCode().isEmpty()) {
        instrCode_ = other.instrCode_;
        onChanged();
      }
      if (other.direct_ != 0) {
        setDirectValue(other.getDirectValue());
      }
      if (other.category_ != 0) {
        setCategoryValue(other.getCategoryValue());
      }
      if (other.product_ != 0) {
        setProductValue(other.getProductValue());
      }
      if (other.orderType_ != 0) {
        setOrderTypeValue(other.getOrderTypeValue());
      }
      if (other.timeInForce_ != 0) {
        setTimeInForceValue(other.getTimeInForceValue());
      }
      if (other.hedge_ != 0) {
        setHedgeValue(other.getHedgeValue());
      }
      if (!other.getReqId().isEmpty()) {
        reqId_ = other.reqId_;
        onChanged();
      }
      if (!other.getExchangeOrderId().isEmpty()) {
        exchangeOrderId_ = other.exchangeOrderId_;
        onChanged();
      }
      if (!other.getServerFlag().isEmpty()) {
        serverFlag_ = other.serverFlag_;
        onChanged();
      }
      if (!other.getExpireTime().isEmpty()) {
        expireTime_ = other.expireTime_;
        onChanged();
      }
      if (other.getIsRisk() != false) {
        setIsRisk(other.getIsRisk());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      QueryOrderReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (QueryOrderReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long sessionId_ ;
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>optional uint64 session_id = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>optional uint64 session_id = 1;</code>
     */
    public Builder setSessionId(long value) {
      
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>optional uint64 session_id = 1;</code>
     */
    public Builder clearSessionId() {
      
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private Object account_ = "";
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public String getAccount() {
      Object ref = account_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        account_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public Builder setAccount(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      account_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public Builder clearAccount() {
      
      account_ = getDefaultInstance().getAccount();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 账户
     * </pre>
     *
     * <code>optional string account = 2;</code>
     */
    public Builder setAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      account_ = value;
      onChanged();
      return this;
    }

    private int exchange_ = 0;
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public int getExchangeValue() {
      return exchange_;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public Builder setExchangeValue(int value) {
      exchange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public com.demo.model.proto.trade.common.ExchangeType getExchange() {
      com.demo.model.proto.trade.common.ExchangeType result = com.demo.model.proto.trade.common.ExchangeType.valueOf(exchange_);
      return result == null ? com.demo.model.proto.trade.common.ExchangeType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public Builder setExchange(com.demo.model.proto.trade.common.ExchangeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      exchange_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易所
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 3;</code>
     */
    public Builder clearExchange() {
      
      exchange_ = 0;
      onChanged();
      return this;
    }

    private Object instrCode_ = "";
    /**
     * <pre>
     * 合约代码
     * </pre>
     *
     * <code>optional string instr_code = 4;</code>
     */
    public String getInstrCode() {
      Object ref = instrCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        instrCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 合约代码
     * </pre>
     *
     * <code>optional string instr_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInstrCodeBytes() {
      Object ref = instrCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        instrCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 合约代码
     * </pre>
     *
     * <code>optional string instr_code = 4;</code>
     */
    public Builder setInstrCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      instrCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 合约代码
     * </pre>
     *
     * <code>optional string instr_code = 4;</code>
     */
    public Builder clearInstrCode() {
      
      instrCode_ = getDefaultInstance().getInstrCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 合约代码
     * </pre>
     *
     * <code>optional string instr_code = 4;</code>
     */
    public Builder setInstrCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      instrCode_ = value;
      onChanged();
      return this;
    }

    private int direct_ = 0;
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.BSDirectType direct = 5;</code>
     */
    public int getDirectValue() {
      return direct_;
    }
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.BSDirectType direct = 5;</code>
     */
    public Builder setDirectValue(int value) {
      direct_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.BSDirectType direct = 5;</code>
     */
    public BSDirectType getDirect() {
      BSDirectType result = BSDirectType.valueOf(direct_);
      return result == null ? BSDirectType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.BSDirectType direct = 5;</code>
     */
    public Builder setDirect(BSDirectType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direct_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 买卖方向
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.BSDirectType direct = 5;</code>
     */
    public Builder clearDirect() {
      
      direct_ = 0;
      onChanged();
      return this;
    }

    private int category_ = 0;
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public int getCategoryValue() {
      return category_;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public Builder setCategoryValue(int value) {
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public com.demo.model.proto.trade.common.CategoryType getCategory() {
      com.demo.model.proto.trade.common.CategoryType result = com.demo.model.proto.trade.common.CategoryType.valueOf(category_);
      return result == null ? com.demo.model.proto.trade.common.CategoryType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public Builder setCategory(com.demo.model.proto.trade.common.CategoryType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      category_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 合约大类
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 6;</code>
     */
    public Builder clearCategory() {
      
      category_ = 0;
      onChanged();
      return this;
    }

    private int product_ = 0;
    /**
     * <pre>
     * 品种类型 
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ProductType product = 7;</code>
     */
    public int getProductValue() {
      return product_;
    }
    /**
     * <pre>
     * 品种类型 
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ProductType product = 7;</code>
     */
    public Builder setProductValue(int value) {
      product_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 品种类型 
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ProductType product = 7;</code>
     */
    public com.demo.model.proto.trade.common.ProductType getProduct() {
      com.demo.model.proto.trade.common.ProductType result = com.demo.model.proto.trade.common.ProductType.valueOf(product_);
      return result == null ? com.demo.model.proto.trade.common.ProductType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 品种类型 
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ProductType product = 7;</code>
     */
    public Builder setProduct(com.demo.model.proto.trade.common.ProductType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      product_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 品种类型 
     * </pre>
     *
     * <code>optional .com.demo.model.proto.trade.common.ProductType product = 7;</code>
     */
    public Builder clearProduct() {
      
      product_ = 0;
      onChanged();
      return this;
    }

    private int orderType_ = 0;
    /**
     * <pre>
     * 委托类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.OrderTypeType order_type = 8;</code>
     */
    public int getOrderTypeValue() {
      return orderType_;
    }
    /**
     * <pre>
     * 委托类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.OrderTypeType order_type = 8;</code>
     */
    public Builder setOrderTypeValue(int value) {
      orderType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 委托类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.OrderTypeType order_type = 8;</code>
     */
    public OrderTypeType getOrderType() {
      OrderTypeType result = OrderTypeType.valueOf(orderType_);
      return result == null ? OrderTypeType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 委托类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.OrderTypeType order_type = 8;</code>
     */
    public Builder setOrderType(OrderTypeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      orderType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 委托类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.OrderTypeType order_type = 8;</code>
     */
    public Builder clearOrderType() {
      
      orderType_ = 0;
      onChanged();
      return this;
    }

    private int timeInForce_ = 0;
    /**
     * <pre>
     * 委托有效类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TimeInForceType time_in_force = 9;</code>
     */
    public int getTimeInForceValue() {
      return timeInForce_;
    }
    /**
     * <pre>
     * 委托有效类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TimeInForceType time_in_force = 9;</code>
     */
    public Builder setTimeInForceValue(int value) {
      timeInForce_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 委托有效类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TimeInForceType time_in_force = 9;</code>
     */
    public TimeInForceType getTimeInForce() {
      TimeInForceType result = TimeInForceType.valueOf(timeInForce_);
      return result == null ? TimeInForceType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 委托有效类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TimeInForceType time_in_force = 9;</code>
     */
    public Builder setTimeInForce(TimeInForceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      timeInForce_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 委托有效类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TimeInForceType time_in_force = 9;</code>
     */
    public Builder clearTimeInForce() {
      
      timeInForce_ = 0;
      onChanged();
      return this;
    }

    private int hedge_ = 0;
    /**
     * <pre>
     * 投保标志
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.HedgeFlagType hedge = 10;</code>
     */
    public int getHedgeValue() {
      return hedge_;
    }
    /**
     * <pre>
     * 投保标志
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.HedgeFlagType hedge = 10;</code>
     */
    public Builder setHedgeValue(int value) {
      hedge_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 投保标志
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.HedgeFlagType hedge = 10;</code>
     */
    public HedgeFlagType getHedge() {
      HedgeFlagType result = HedgeFlagType.valueOf(hedge_);
      return result == null ? HedgeFlagType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 投保标志
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.HedgeFlagType hedge = 10;</code>
     */
    public Builder setHedge(HedgeFlagType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      hedge_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 投保标志
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.HedgeFlagType hedge = 10;</code>
     */
    public Builder clearHedge() {
      
      hedge_ = 0;
      onChanged();
      return this;
    }

    private Object reqId_ = "";
    /**
     * <pre>
     * 请求ID 
     * </pre>
     *
     * <code>optional string req_id = 11;</code>
     */
    public String getReqId() {
      Object ref = reqId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 请求ID 
     * </pre>
     *
     * <code>optional string req_id = 11;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      Object ref = reqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 请求ID 
     * </pre>
     *
     * <code>optional string req_id = 11;</code>
     */
    public Builder setReqId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求ID 
     * </pre>
     *
     * <code>optional string req_id = 11;</code>
     */
    public Builder clearReqId() {
      
      reqId_ = getDefaultInstance().getReqId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求ID 
     * </pre>
     *
     * <code>optional string req_id = 11;</code>
     */
    public Builder setReqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reqId_ = value;
      onChanged();
      return this;
    }

    private Object exchangeOrderId_ = "";
    /**
     * <pre>
     * 交易所委托序号
     * </pre>
     *
     * <code>optional string exchange_order_id = 12;</code>
     */
    public String getExchangeOrderId() {
      Object ref = exchangeOrderId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        exchangeOrderId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 交易所委托序号
     * </pre>
     *
     * <code>optional string exchange_order_id = 12;</code>
     */
    public com.google.protobuf.ByteString
        getExchangeOrderIdBytes() {
      Object ref = exchangeOrderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        exchangeOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 交易所委托序号
     * </pre>
     *
     * <code>optional string exchange_order_id = 12;</code>
     */
    public Builder setExchangeOrderId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exchangeOrderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易所委托序号
     * </pre>
     *
     * <code>optional string exchange_order_id = 12;</code>
     */
    public Builder clearExchangeOrderId() {
      
      exchangeOrderId_ = getDefaultInstance().getExchangeOrderId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易所委托序号
     * </pre>
     *
     * <code>optional string exchange_order_id = 12;</code>
     */
    public Builder setExchangeOrderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exchangeOrderId_ = value;
      onChanged();
      return this;
    }

    private Object serverFlag_ = "";
    /**
     * <pre>
     * 服务器标识(易盛接口使用)
     * </pre>
     *
     * <code>optional string server_flag = 13;</code>
     */
    public String getServerFlag() {
      Object ref = serverFlag_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverFlag_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 服务器标识(易盛接口使用)
     * </pre>
     *
     * <code>optional string server_flag = 13;</code>
     */
    public com.google.protobuf.ByteString
        getServerFlagBytes() {
      Object ref = serverFlag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverFlag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 服务器标识(易盛接口使用)
     * </pre>
     *
     * <code>optional string server_flag = 13;</code>
     */
    public Builder setServerFlag(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 服务器标识(易盛接口使用)
     * </pre>
     *
     * <code>optional string server_flag = 13;</code>
     */
    public Builder clearServerFlag() {
      
      serverFlag_ = getDefaultInstance().getServerFlag();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 服务器标识(易盛接口使用)
     * </pre>
     *
     * <code>optional string server_flag = 13;</code>
     */
    public Builder setServerFlagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverFlag_ = value;
      onChanged();
      return this;
    }

    private Object expireTime_ = "";
    /**
     * <pre>
     * 委托过期时间(GTD)时需要 日期时间戳
     * </pre>
     *
     * <code>optional string expire_time = 14;</code>
     */
    public String getExpireTime() {
      Object ref = expireTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        expireTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 委托过期时间(GTD)时需要 日期时间戳
     * </pre>
     *
     * <code>optional string expire_time = 14;</code>
     */
    public com.google.protobuf.ByteString
        getExpireTimeBytes() {
      Object ref = expireTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        expireTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 委托过期时间(GTD)时需要 日期时间戳
     * </pre>
     *
     * <code>optional string expire_time = 14;</code>
     */
    public Builder setExpireTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expireTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 委托过期时间(GTD)时需要 日期时间戳
     * </pre>
     *
     * <code>optional string expire_time = 14;</code>
     */
    public Builder clearExpireTime() {
      
      expireTime_ = getDefaultInstance().getExpireTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 委托过期时间(GTD)时需要 日期时间戳
     * </pre>
     *
     * <code>optional string expire_time = 14;</code>
     */
    public Builder setExpireTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      expireTime_ = value;
      onChanged();
      return this;
    }

    private boolean isRisk_ ;
    /**
     * <pre>
     * 是否是风险单
     * </pre>
     *
     * <code>optional bool is_risk = 15;</code>
     */
    public boolean getIsRisk() {
      return isRisk_;
    }
    /**
     * <pre>
     * 是否是风险单
     * </pre>
     *
     * <code>optional bool is_risk = 15;</code>
     */
    public Builder setIsRisk(boolean value) {
      
      isRisk_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否是风险单
     * </pre>
     *
     * <code>optional bool is_risk = 15;</code>
     */
    public Builder clearIsRisk() {
      
      isRisk_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.demo.model.proto.gateway.QueryOrderReq)
  }

  // @@protoc_insertion_point(class_scope:com.demo.model.proto.gateway.QueryOrderReq)
  private static final QueryOrderReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueryOrderReq();
  }

  public static QueryOrderReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryOrderReq>
      PARSER = new com.google.protobuf.AbstractParser<QueryOrderReq>() {
    public QueryOrderReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryOrderReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryOrderReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<QueryOrderReq> getParserForType() {
    return PARSER;
  }

  public QueryOrderReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

