// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

public interface QueryFeeRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.gateway.QueryFeeRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 资金账号
   * </pre>
   *
   * <code>optional string account = 3;</code>
   */
  String getAccount();
  /**
   * <pre>
   * 资金账号
   * </pre>
   *
   * <code>optional string account = 3;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <pre>
   * 交易所id
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 4;</code>
   */
  int getExchangeValue();
  /**
   * <pre>
   * 交易所id
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 4;</code>
   */
  com.demo.model.proto.trade.common.ExchangeType getExchange();

  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>optional string instr_code = 5;</code>
   */
  String getInstrCode();
  /**
   * <pre>
   * 证券代码
   * </pre>
   *
   * <code>optional string instr_code = 5;</code>
   */
  com.google.protobuf.ByteString
      getInstrCodeBytes();

  /**
   * <pre>
   * 总费用
   * </pre>
   *
   * <code>optional uint64 charge = 6;</code>
   */
  long getCharge();

  /**
   * <pre>
   * 费用名称
   * </pre>
   *
   * <code>optional string name = 7;</code>
   */
  String getName();
  /**
   * <pre>
   * 费用名称
   * </pre>
   *
   * <code>optional string name = 7;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 费用数值
   * </pre>
   *
   * <code>optional uint64 amt = 8;</code>
   */
  long getAmt();

  /**
   * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 9;</code>
   */
  boolean hasRet();
  /**
   * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 9;</code>
   */
  TradeRetCode getRet();
  /**
   * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 9;</code>
   */
  TradeRetCodeOrBuilder getRetOrBuilder();
}
