// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

public interface QueryContractReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.gateway.QueryContractReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>optional uint64 session_id = 1;</code>
   */
  long getSessionId();

  /**
   * <pre>
   * 交易所编码
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 2;</code>
   */
  int getExchangeValue();
  /**
   * <pre>
   * 交易所编码
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.ExchangeType exchange = 2;</code>
   */
  com.demo.model.proto.trade.common.ExchangeType getExchange();

  /**
   * <pre>
   * 品种类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 3;</code>
   */
  int getCategoryValue();
  /**
   * <pre>
   * 品种类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.trade.common.CategoryType category = 3;</code>
   */
  com.demo.model.proto.trade.common.CategoryType getCategory();

  /**
   * <pre>
   * 品种编号
   * </pre>
   *
   * <code>optional string commodity = 4;</code>
   */
  String getCommodity();
  /**
   * <pre>
   * 品种编号
   * </pre>
   *
   * <code>optional string commodity = 4;</code>
   */
  com.google.protobuf.ByteString
      getCommodityBytes();

  /**
   * <pre>
   * 账号
   * </pre>
   *
   * <code>optional string account = 5;</code>
   */
  String getAccount();
  /**
   * <pre>
   * 账号
   * </pre>
   *
   * <code>optional string account = 5;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();
}
