// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

public final class TradeMsgDef {
  private TradeMsgDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_AccountInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_AccountInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_TradeRetCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_TradeRetCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_AccountHeartBeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_AccountHeartBeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_AccountHearBeatRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_AccountHearBeatRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_UsrLoginReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_UsrLoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_UsrLoginRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_UsrLoginRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_APIReadyRtn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_APIReadyRtn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_UsrLogoutReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_UsrLogoutReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_UsrLogoutRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_UsrLogoutRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_ModPassWordReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_ModPassWordReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_ModPassWordRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_ModPassWordRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryLoginStatusReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryLoginStatusReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryLoginStatusRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryLoginStatusRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryFutureBalanceReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryFutureBalanceReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_FutureBalance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_FutureBalance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryFutureBalanceRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryFutureBalanceRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryOrderReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryOrderReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_FutureOrderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_FutureOrderInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryOrderRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryOrderRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_AccountFeeRent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_AccountFeeRent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_AccountMarginRentInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_AccountMarginRentInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryPositionSummaryReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryPositionSummaryReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_PositionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_PositionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryPositionSummaryRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryPositionSummaryRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryPositionReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryPositionReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryPositionRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryPositionRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryMatchReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryMatchReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_MatchInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_MatchInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryMatchRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryMatchRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryHisOrderReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryHisOrderReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_HisOrderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_HisOrderInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryHisOrderRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryHisOrderRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryHisMatchReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryHisMatchReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_HisMatchInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_HisMatchInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryHisMatchRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryHisMatchRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryHisPositionReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryHisPositionReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryHisPositionRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryHisPositionRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_InsertOrderReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_InsertOrderReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_InsertOrderRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_InsertOrderRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_CancelOrderReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_CancelOrderReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_CancelOrderRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_CancelOrderRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_ModOrderReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_ModOrderReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_ModOrderRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_ModOrderRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_PositionProfit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_PositionProfit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_PositionProfits_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_PositionProfits_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_AccountDisConnect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_AccountDisConnect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryFeeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryFeeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryFeeRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryFeeRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryCommodityReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryCommodityReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_CommodityInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_CommodityInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryCommodityRsps_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryCommodityRsps_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryContractReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryContractReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_ContractInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_ContractInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryContractRsps_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryContractRsps_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryCurrencyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryCurrencyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_CurrencyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_CurrencyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryCurrencyRsps_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryCurrencyRsps_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryExchangeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryExchangeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_ExchangeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_ExchangeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_QueryExchangeRsps_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_QueryExchangeRsps_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_ContactInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_ContactInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_VertificateCodeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_VertificateCodeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_VertificateCodeRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_VertificateCodeRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_gateway_SetVertificateCodeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_gateway_SetVertificateCodeReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023trade_msg_def.proto\022\034com.demo.model.pr" +
      "oto.gateway\032\033trade_common_type_def.proto" +
      "\032\024trade_type_def.proto\"\207\002\n\017TradeMsgCarri" +
      "er\022\021\n\tseries_id\030\001 \001(\004\0228\n\004type\030\002 \001(\0162*.co" +
      "m.demo.model.proto.gateway.TradeMsgType\022" +
      ";\n\007version\030\003 \001(\0162*.com.demo.model.proto." +
      "gateway.ProtoVersion\0227\n\003ret\030\004 \001(\0132*.com." +
      "demo.model.proto.gateway.TradeRetCode\022\014\n" +
      "\004data\030\005 \001(\014\022\020\n\010platform\030\006 \001(\t\022\021\n\tdevice_" +
      "id\030\007 \001(\t\"\036\n\013AccountInfo\022\017\n\007account\030\001 \001(\t",
      "\"V\n\014TradeRetCode\0229\n\004code\030\001 \001(\0162+.com.dem" +
      "o.model.proto.gateway.TreadeRetCode\022\013\n\003m" +
      "sg\030\002 \001(\t\":\n\023AccountHeartBeatReq\022\022\n\nsessi" +
      "on_id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\"^\n\022AccountH" +
      "earBeatRsp\0227\n\003ret\030\001 \001(\0132*.com.demo.model" +
      ".proto.gateway.TradeRetCode\022\017\n\007account\030\003" +
      " \001(\t\"d\n\013UsrLoginReq\022\017\n\007account\030\001 \001(\t\022\013\n\003" +
      "pwd\030\002 \001(\t\022\017\n\007new_pwd\030\003 \001(\t\022\022\n\nip_address" +
      "\030\004 \001(\t\022\022\n\nchange_pwd\030\005 \001(\010\"\215\002\n\013UsrLoginR" +
      "sp\0227\n\003ret\030\001 \001(\0132*.com.demo.model.proto.g",
      "ateway.TradeRetCode\022\022\n\nsession_id\030\002 \001(\004\022" +
      "\017\n\007account\030\003 \001(\t\022\025\n\rlast_login_ip\030\004 \001(\t\022" +
      "\027\n\017last_login_time\030\005 \001(\t\022\030\n\020last_logout_" +
      "time\030\006 \001(\t\022\027\n\017is_need_mod_pwd\030\007 \001(\010\022\022\n\nt" +
      "rade_date\030\010 \001(\t\022\030\n\020last_settle_time\030\t \001(" +
      "\t\022\017\n\007contact\030\n \003(\t\"W\n\013APIReadyRtn\0227\n\003ret" +
      "\030\001 \001(\0132*.com.demo.model.proto.gateway.Tr" +
      "adeRetCode\022\017\n\007account\030\002 \001(\t\"A\n\014UsrLogout" +
      "Req\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t" +
      "\022\014\n\004site\030\003 \001(\t\"X\n\014UsrLogoutRsp\0227\n\003ret\030\001 ",
      "\001(\0132*.com.demo.model.proto.gateway.Trade" +
      "RetCode\022\017\n\007account\030\002 \001(\t\"W\n\016ModPassWordR" +
      "eq\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\022" +
      "\017\n\007old_pwd\030\003 \001(\t\022\017\n\007new_pwd\030\004 \001(\t\"Z\n\016Mod" +
      "PassWordRsp\0227\n\003ret\030\001 \001(\0132*.com.demo.mode" +
      "l.proto.gateway.TradeRetCode\022\017\n\007account\030" +
      "\002 \001(\t\":\n\023QueryLoginStatusReq\022\022\n\nsession_" +
      "id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\"v\n\023QueryLoginS" +
      "tatusRsp\0227\n\003ret\030\001 \001(\0132*.com.demo.model.p" +
      "roto.gateway.TradeRetCode\022\017\n\007account\030\002 \001",
      "(\t\022\025\n\ris_disconnect\030\003 \001(\010\"<\n\025QueryFuture" +
      "BalanceReq\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007accoun" +
      "t\030\002 \001(\t\"\354\007\n\rFutureBalance\022\017\n\007account\030\001 \001" +
      "(\t\022\014\n\004name\030\002 \001(\t\022\021\n\tprecision\030\003 \001(\r\022A\n\010c" +
      "urrency\030\004 \001(\0162/.com.demo.model.proto.tra" +
      "de.common.CurrencyType\022\023\n\013pre_balance\030\005 " +
      "\001(\003\022\030\n\020pre_unexp_profit\030\006 \001(\003\022\037\n\027pre_lme" +
      "_position_profit\030\007 \001(\003\022\022\n\npre_equity\030\010 \001" +
      "(\003\022\025\n\rpre_available\030\t \001(\003\022\030\n\020pre_maket_e" +
      "quity\030\n \001(\003\022\021\n\tavailable\030\013 \001(\003\022\021\n\twith_d",
      "raw\030\014 \001(\003\022\024\n\014adjust_value\030\r \001(\003\022\017\n\007pledg" +
      "ed\030\016 \001(\003\022\022\n\ncommission\030\017 \001(\003\022\013\n\003fee\030\020 \001(" +
      "\003\022\023\n\013account_fee\030\021 \001(\003\022\022\n\nbuy_freeze\030\022 \001" +
      "(\003\022\031\n\021buy_freeze_margin\030\023 \001(\003\022\022\n\nfreeze_" +
      "fee\030\024 \001(\003\022\023\n\013sell_freeze\030\025 \001(\003\022\032\n\022sell_f" +
      "reeze_margin\030\026 \001(\003\022\024\n\014close_profit\030\027 \001(\003" +
      "\022\024\n\014unexp_profit\030\030 \001(\003\022\022\n\nexp_profit\030\031 \001" +
      "(\003\022\027\n\017position_profit\030\032 \001(\003\022\033\n\023lme_posit" +
      "ion_profit\030\033 \001(\003\022\026\n\016initial_margin\030\034 \001(\003" +
      "\022\032\n\022maintenance_margin\030\035 \001(\003\022\033\n\023upper_in",
      "ital_margin\030\036 \001(\003\022 \n\030upper_maintenance_m" +
      "argin\030\037 \001(\003\022\020\n\010discount\030  \001(\003\022\017\n\007deposit" +
      "\030! \001(\003\022\017\n\007drawing\030\" \001(\003\022\025\n\rswap_in_value" +
      "\030# \001(\003\022\026\n\016swap_out_value\030$ \001(\003\022\026\n\016premiu" +
      "m_income\030% \001(\003\022\023\n\013premium_pay\030& \001(\003\022\017\n\007b" +
      "alance\030\' \001(\003\022\016\n\006equity\030( \001(\003\022\025\n\rmarket_e" +
      "quity\030) \001(\003\022\022\n\nauth_value\030* \001(\003\022\025\n\rexcha" +
      "nge_rate\030+ \001(\003\"\342\001\n\025QueryFutureBalanceRsp" +
      "\0227\n\003ret\030\001 \001(\0132*.com.demo.model.proto.gat" +
      "eway.TradeRetCode\022\017\n\007account\030\002 \001(\t\022@\n\013su",
      "m_balance\030\003 \001(\0132+.com.demo.model.proto.g" +
      "ateway.FutureBalance\022=\n\010balances\030\004 \003(\0132+" +
      ".com.demo.model.proto.gateway.FutureBala" +
      "nce\"\364\004\n\rQueryOrderReq\022\022\n\nsession_id\030\001 \001(" +
      "\004\022\017\n\007account\030\002 \001(\t\022A\n\010exchange\030\003 \001(\0162/.c" +
      "om.demo.model.proto.trade.common.Exchang" +
      "eType\022\022\n\ninstr_code\030\004 \001(\t\022:\n\006direct\030\005 \001(" +
      "\0162*.com.demo.model.proto.gateway.BSDirec" +
      "tType\022A\n\010category\030\006 \001(\0162/.com.demo.model" +
      ".proto.trade.common.CategoryType\022?\n\007prod",
      "uct\030\007 \001(\0162..com.demo.model.proto.trade.c" +
      "ommon.ProductType\022?\n\norder_type\030\010 \001(\0162+." +
      "com.demo.model.proto.gateway.OrderTypeTy" +
      "pe\022D\n\rtime_in_force\030\t \001(\0162-.com.demo.mod" +
      "el.proto.gateway.TimeInForceType\022:\n\005hedg" +
      "e\030\n \001(\0162+.com.demo.model.proto.gateway.H" +
      "edgeFlagType\022\016\n\006req_id\030\013 \001(\t\022\031\n\021exchange" +
      "_order_id\030\014 \001(\t\022\023\n\013server_flag\030\r \001(\t\022\023\n\013" +
      "expire_time\030\016 \001(\t\022\017\n\007is_risk\030\017 \001(\010\"\370\t\n\017F" +
      "utureOrderInfo\022\017\n\007account\030\001 \001(\t\022A\n\010excha",
      "nge\030\002 \001(\0162/.com.demo.model.proto.trade.c" +
      "ommon.ExchangeType\022\022\n\ninstr_code\030\003 \001(\t\022:" +
      "\n\006direct\030\004 \001(\0162*.com.demo.model.proto.ga" +
      "teway.BSDirectType\022A\n\010category\030\005 \001(\0162/.c" +
      "om.demo.model.proto.trade.common.Categor" +
      "yType\022?\n\007product\030\006 \001(\0162..com.demo.model." +
      "proto.trade.common.ProductType\022\021\n\tprecis" +
      "ion\030\007 \001(\r\022?\n\norder_type\030\t \001(\0162+.com.demo" +
      ".model.proto.gateway.OrderTypeType\022D\n\rti" +
      "me_in_force\030\n \001(\0162-.com.demo.model.proto",
      ".gateway.TimeInForceType\022\023\n\013expire_time\030" +
      "\013 \001(\t\022\017\n\007is_risk\030\014 \001(\010\022A\n\017position_effec" +
      "t\030\r \001(\0162(.com.demo.model.proto.gateway.O" +
      "ffsetType\022:\n\005hedge\030\016 \001(\0162+.com.demo.mode" +
      "l.proto.gateway.HedgeFlagType\022\r\n\005price\030\017" +
      " \001(\003\022\023\n\013match_price\030\020 \001(\003\022\022\n\nstop_price\030" +
      "\021 \001(\003\022\013\n\003vol\030\022 \001(\r\022<\n\005state\030\023 \001(\0162-.com." +
      "demo.model.proto.gateway.OrderStatusType" +
      "\022\025\n\raverage_price\030\024 \001(\003\022\021\n\tmatch_qty\030\025 \001" +
      "(\r\022\020\n\010order_no\030\026 \001(\t\022\025\n\rmin_clip_size\030\027 ",
      "\001(\r\022\025\n\rmax_clip_size\030\030 \001(\r\022\022\n\ncalcel_qty" +
      "\030\031 \001(\r\022\027\n\017order_stream_id\030\032 \001(\t\022\020\n\010upper" +
      "_no\030\033 \001(\t\022\030\n\020upper_channel_no\030\034 \001(\t\022\020\n\010l" +
      "ocal_no\030\035 \001(\t\022\027\n\017upper_stream_no\030\036 \001(\t\022\022" +
      "\n\nis_add_one\030\037 \001(\t\022\020\n\010usr_data\030  \001(\004\022\021\n\t" +
      "system_no\030! \001(\t\022\032\n\022exchange_system_no\030\" " +
      "\001(\t\022\030\n\020parent_system_no\030# \001(\t\022\023\n\013insert_" +
      "time\030$ \001(\t\022\023\n\013update_time\030% \001(\t\022\023\n\013serve" +
      "r_flag\030& \001(\t\022\022\n\nerror_code\030\' \001(\r\022\022\n\nerro" +
      "r_text\030( \001(\t\0227\n\003ret\030) \001(\0132*.com.demo.mod",
      "el.proto.gateway.TradeRetCode\"\230\001\n\rQueryO" +
      "rderRsp\0227\n\003ret\030\001 \001(\0132*.com.demo.model.pr" +
      "oto.gateway.TradeRetCode\022\017\n\007account\030\002 \001(" +
      "\t\022=\n\006orders\030\003 \003(\0132-.com.demo.model.proto" +
      ".gateway.FutureOrderInfo\"=\n\026QueryAccount" +
      "FeeRentReq\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007accoun" +
      "t\030\002 \001(\t\"\317\003\n\016AccountFeeRent\022\017\n\007account\030\001 " +
      "\001(\t\022A\n\010exchange\030\002 \001(\0162/.com.demo.model.p" +
      "roto.trade.common.ExchangeType\022\024\n\014produc" +
      "t_code\030\003 \001(\t\022A\n\010category\030\004 \001(\0162/.com.dem",
      "o.model.proto.trade.common.CategoryType\022" +
      "=\n\004type\030\005 \001(\0162/.com.demo.model.proto.gat" +
      "eway.CalculateModeType\022A\n\010currency\030\006 \001(\016" +
      "2/.com.demo.model.proto.trade.common.Cur" +
      "rencyType\022J\n\021currency_group_no\030\007 \001(\0162/.c" +
      "om.demo.model.proto.trade.common.Currenc" +
      "yType\022\026\n\016open_close_fee\030\010 \001(\004\022\027\n\017close_t" +
      "oday_fee\030\t \001(\004\022\021\n\tprecision\030\n \001(\r\"\242\001\n\026Qu" +
      "eryAccountFeeRentRsp\0227\n\003ret\030\001 \001(\0132*.com." +
      "demo.model.proto.gateway.TradeRetCode\022\017\n",
      "\007account\030\002 \001(\t\022>\n\010fee_info\030\003 \003(\0132,.com.d" +
      "emo.model.proto.gateway.AccountFeeRent\"\334" +
      "\001\n\031QueryAccountMarginRentReq\022\022\n\nsession_" +
      "id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\022A\n\010exchange\030\003 " +
      "\001(\0162/.com.demo.model.proto.trade.common." +
      "ExchangeType\022\024\n\014product_code\030\004 \001(\t\022A\n\010ca" +
      "tegory\030\006 \001(\0162/.com.demo.model.proto.trad" +
      "e.common.CategoryType\"\352\003\n\025AccountMarginR" +
      "entInfo\022\017\n\007account\030\001 \001(\t\022A\n\010exchange\030\002 \001" +
      "(\0162/.com.demo.model.proto.trade.common.E",
      "xchangeType\022\024\n\014product_code\030\003 \001(\t\022A\n\010cat" +
      "egory\030\004 \001(\0162/.com.demo.model.proto.trade" +
      ".common.CategoryType\022\022\n\ninstr_code\030\005 \001(\t" +
      "\022A\n\010currency\030\006 \001(\0162/.com.demo.model.prot" +
      "o.trade.common.CurrencyType\022=\n\004type\030\007 \001(" +
      "\0162/.com.demo.model.proto.gateway.Calcula" +
      "teModeType\022\026\n\016initial_margin\030\010 \001(\004\022\032\n\022ma" +
      "intenance_margin\030\t \001(\004\022\030\n\020sell_init_marg" +
      "in\030\n \001(\004\022\030\n\020sell_main_margin\030\013 \001(\004\022\023\n\013lo" +
      "ck_margin\030\014 \001(\004\022\021\n\tprecision\030\r \001(\r\"\260\001\n\031Q",
      "ueryAccountMarginRentRsp\0227\n\003ret\030\001 \001(\0132*." +
      "com.demo.model.proto.gateway.TradeRetCod" +
      "e\022\017\n\007account\030\002 \001(\t\022I\n\014margin_infos\030\003 \003(\013" +
      "23.com.demo.model.proto.gateway.AccountM" +
      "arginRentInfo\"\274\001\n\027QueryPositionSummaryRe" +
      "q\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\022A" +
      "\n\010exchange\030\003 \001(\0162/.com.demo.model.proto." +
      "trade.common.ExchangeType\022\022\n\ninstr_code\030" +
      "\004 \001(\t\022\020\n\010page_num\030\005 \001(\r\022\023\n\013request_num\030\006" +
      " \001(\r\"\313\006\n\014PositionInfo\022\017\n\007account\030\001 \001(\t\022A",
      "\n\010exchange\030\002 \001(\0162/.com.demo.model.proto." +
      "trade.common.ExchangeType\022\022\n\ninstr_code\030" +
      "\003 \001(\t\022A\n\010currency\030\004 \001(\0162/.com.demo.model" +
      ".proto.trade.common.CurrencyType\022\021\n\tprec" +
      "ision\030\005 \001(\r\022\020\n\010position\030\006 \001(\005\022\026\n\016positio" +
      "n_price\030\007 \001(\003\022\017\n\007average\030\010 \001(\003\022\021\n\topen_c" +
      "ost\030\t \001(\003\022\027\n\017position_profit\030\n \001(\003\022\033\n\023lm" +
      "e_position_profit\030\013 \001(\003\022\027\n\017calculate_pri" +
      "ce\030\014 \001(\003\022\026\n\016initial_margin\030\r \001(\004\022\032\n\022main" +
      "tenance_margin\030\016 \001(\004\022\033\n\023upper_inital_mar",
      "gin\030\017 \001(\004\022 \n\030upper_maintenance_margin\030\020 " +
      "\001(\004\022<\n\010pos_type\030\021 \001(\0162*.com.demo.model.p" +
      "roto.gateway.PositionType\022\022\n\npre_margin\030" +
      "\022 \001(\004\022\023\n\013used_margin\030\023 \001(\004\022:\n\006direct\030\024 \001" +
      "(\0162*.com.demo.model.proto.gateway.BSDire" +
      "ctType\022:\n\005hedge\030\025 \001(\0162+.com.demo.model.p" +
      "roto.gateway.HedgeFlagType\022\023\n\013position_n" +
      "o\030\026 \001(\t\022\023\n\013server_flag\030\027 \001(\t\022\020\n\010order_no" +
      "\030\030 \001(\t\022\020\n\010match_id\030\031 \001(\t\022\020\n\010upper_no\030\032 \001" +
      "(\t\022\032\n\022position_stream_no\030\033 \001(\t\022\022\n\nlocal_",
      "time\030\034 \001(\004\"\242\001\n\027QueryPositionSummaryRsp\0227" +
      "\n\003ret\030\001 \001(\0132*.com.demo.model.proto.gatew" +
      "ay.TradeRetCode\022\017\n\007account\030\002 \001(\t\022=\n\tposi" +
      "tions\030\003 \003(\0132*.com.demo.model.proto.gatew" +
      "ay.PositionInfo\"\265\001\n\020QueryPositionReq\022\022\n\n" +
      "session_id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\022A\n\010exc" +
      "hange\030\003 \001(\0162/.com.demo.model.proto.trade" +
      ".common.ExchangeType\022\022\n\ninstr_code\030\004 \001(\t" +
      "\022\020\n\010page_num\030\005 \001(\r\022\023\n\013request_num\030\006 \001(\r\"" +
      "\233\001\n\020QueryPositionRsp\0227\n\003ret\030\001 \001(\0132*.com.",
      "demo.model.proto.gateway.TradeRetCode\022\017\n" +
      "\007account\030\002 \001(\t\022=\n\tpositions\030\003 \003(\0132*.com." +
      "demo.model.proto.gateway.PositionInfo\"\336\003" +
      "\n\rQueryMatchReq\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007a" +
      "ccount\030\002 \001(\t\022A\n\010exchange\030\003 \001(\0162/.com.dem" +
      "o.model.proto.trade.common.ExchangeType\022" +
      "\022\n\ninstr_code\030\004 \001(\t\022A\n\010category\030\005 \001(\0162/." +
      "com.demo.model.proto.trade.common.Catego" +
      "ryType\022?\n\007product\030\006 \001(\0162..com.demo.model" +
      ".proto.trade.common.ProductType\022:\n\006direc",
      "t\030\007 \001(\0162*.com.demo.model.proto.gateway.B" +
      "SDirectType\022A\n\017position_effect\030\010 \001(\0162(.c" +
      "om.demo.model.proto.gateway.OffsetType\022\020" +
      "\n\010upper_no\030\t \001(\t\022\023\n\013exchange_no\030\n \001(\t\022\022\n" +
      "\nis_add_one\030\013 \001(\t\022\023\n\013server_flag\030\014 \001(\t\"\256" +
      "\006\n\tMatchInfo\022\017\n\007account\030\001 \001(\t\022\022\n\ninstr_c" +
      "ode\030\002 \001(\t\022A\n\010exchange\030\003 \001(\0162/.com.demo.m" +
      "odel.proto.trade.common.ExchangeType\022A\n\010" +
      "currency\030\004 \001(\0162/.com.demo.model.proto.tr" +
      "ade.common.CurrencyType\022A\n\010category\030\005 \001(",
      "\0162/.com.demo.model.proto.trade.common.Ca" +
      "tegoryType\022?\n\007product\030\006 \001(\0162..com.demo.m" +
      "odel.proto.trade.common.ProductType\022\021\n\tp" +
      "recision\030\007 \001(\r\022:\n\006direct\030\010 \001(\0162*.com.dem" +
      "o.model.proto.gateway.BSDirectType\0228\n\006of" +
      "fset\030\t \001(\0162(.com.demo.model.proto.gatewa" +
      "y.OffsetType\022\014\n\004date\030\n \001(\t\022\013\n\003vol\030\013 \001(\004\022" +
      "\r\n\005price\030\014 \001(\003\022\023\n\013server_flag\030\r \001(\t\022\020\n\010o" +
      "rder_no\030\016 \001(\t\022\027\n\017order_system_no\030\017 \001(\t\022\020" +
      "\n\010match_no\030\020 \001(\t\022\026\n\016upper_match_no\030\021 \001(\t",
      "\022\030\n\020exchage_match_no\030\022 \001(\t\022\027\n\017match_data" +
      "_time\030\023 \001(\t\022\034\n\024upper_match_datetime\030\024 \001(" +
      "\t\022\020\n\010upper_no\030\025 \001(\t\022\026\n\016order_local_id\030\026 " +
      "\001(\t\022\031\n\021exchange_order_no\030\027 \001(\t\022\022\n\nis_add" +
      "_one\030\031 \001(\t\022\022\n\ncommission\030\032 \001(\004\022\027\n\017close_" +
      "pos_price\030\033 \001(\003\"\222\001\n\rQueryMatchRsp\0227\n\003ret" +
      "\030\001 \001(\0132*.com.demo.model.proto.gateway.Tr" +
      "adeRetCode\022\017\n\007account\030\002 \001(\t\0227\n\006matchs\030\003 " +
      "\003(\0132\'.com.demo.model.proto.gateway.Match" +
      "Info\"]\n\020QueryHisOrderReq\022\022\n\nsession_id\030\001",
      " \001(\004\022\017\n\007account\030\002 \001(\t\022\022\n\nbegin_date\030\003 \001(" +
      "\t\022\020\n\010end_date\030\004 \001(\t\"\373\007\n\014HisOrderInfo\022\014\n\004" +
      "date\030\002 \001(\t\022\017\n\007account\030\003 \001(\t\022\022\n\ninstr_cod" +
      "e\030\004 \001(\t\022A\n\010category\030\005 \001(\0162/.com.demo.mod" +
      "el.proto.trade.common.CategoryType\022A\n\010ex" +
      "change\030\006 \001(\0162/.com.demo.model.proto.trad" +
      "e.common.ExchangeType\022\021\n\tprecision\030\007 \001(\r" +
      "\022\024\n\014strike_price\030\010 \001(\003\022?\n\norder_type\030\t \001" +
      "(\0162+.com.demo.model.proto.gateway.OrderT" +
      "ypeType\022D\n\rtime_in_force\030\n \001(\0162-.com.dem",
      "o.model.proto.gateway.TimeInForceType\022\023\n" +
      "\013expire_time\030\013 \001(\t\022\025\n\ris_risk_order\030\014 \001(" +
      "\010\022>\n\norder_side\030\r \001(\0162*.com.demo.model.p" +
      "roto.gateway.BSDirectType\022A\n\017position_ef" +
      "fect\030\016 \001(\0162(.com.demo.model.proto.gatewa" +
      "y.OffsetType\022?\n\nhedge_flag\030\017 \001(\0162+.com.d" +
      "emo.model.proto.gateway.HedgeFlagType\022\023\n" +
      "\013order_price\030\020 \001(\003\022\022\n\nstop_price\030\021 \001(\003\022\021" +
      "\n\torder_qty\030\022 \001(\r\022\025\n\rorder_min_qty\030\023 \001(\r" +
      "\022\032\n\022order_canceled_qty\030\024 \001(\r\022\023\n\013server_f",
      "lag\030\025 \001(\t\022\020\n\010order_no\030\026 \001(\t\022\031\n\021order_ins" +
      "ert_time\030\027 \001(\t\022\031\n\021order_update_time\030\030 \001(" +
      "\t\022H\n\021order_status_type\030\031 \001(\0162-.com.demo." +
      "model.proto.gateway.OrderStatusType\022\023\n\013m" +
      "atch_price\030\032 \001(\003\022\021\n\tmatch_qty\030\033 \001(\r\022\022\n\ni" +
      "s_add_one\030\034 \001(\t\022\030\n\020add_one_is_valid\030\035 \001(" +
      "\010\022\022\n\nerror_code\030\036 \001(\r\022\022\n\nerror_text\030\037 \001(" +
      "\t\"\230\001\n\020QueryHisOrderRsp\0227\n\003ret\030\001 \001(\0132*.co" +
      "m.demo.model.proto.gateway.TradeRetCode\022" +
      "\017\n\007account\030\002 \001(\t\022:\n\006orders\030\003 \003(\0132*.com.d",
      "emo.model.proto.gateway.HisOrderInfo\"]\n\020" +
      "QueryHisMatchReq\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007" +
      "account\030\002 \001(\t\022\022\n\nbegin_date\030\003 \001(\t\022\020\n\010end" +
      "_date\030\004 \001(\t\"\275\006\n\014HisMatchInfo\022\022\n\ntrade_da" +
      "te\030\001 \001(\t\022\017\n\007account\030\002 \001(\t\022\022\n\ninstr_code\030" +
      "\003 \001(\t\022A\n\010category\030\004 \001(\0162/.com.demo.model" +
      ".proto.trade.common.CategoryType\022A\n\010exch" +
      "ange\030\005 \001(\0162/.com.demo.model.proto.trade." +
      "common.ExchangeType\022\021\n\tprecision\030\006 \001(\r\022\024" +
      "\n\014strike_price\030\007 \001(\003\022>\n\nmatch_side\030\010 \001(\016",
      "2*.com.demo.model.proto.gateway.BSDirect" +
      "Type\022A\n\017position_effect\030\t \001(\0162(.com.demo" +
      ".model.proto.gateway.OffsetType\022?\n\nhedge" +
      "_flag\030\n \001(\0162+.com.demo.model.proto.gatew" +
      "ay.HedgeFlagType\022\023\n\013server_flag\030\013 \001(\t\022\020\n" +
      "\010order_no\030\014 \001(\t\022\023\n\013match_price\030\r \001(\003\022\021\n\t" +
      "match_qty\030\016 \001(\r\022\023\n\013settle_date\030\017 \001(\t\022\020\n\010" +
      "match_no\030\020 \001(\t\022\020\n\010turnover\030\021 \001(\004\022\026\n\016prem" +
      "ium_income\030\022 \001(\004\022\023\n\013premium_pay\030\023 \001(\004\022\023\n" +
      "\013account_fee\030\024 \001(\004\022\027\n\017match_date_time\030\025 ",
      "\001(\t\022\035\n\025upper_match_date_time\030\026 \001(\t\022\024\n\014cl" +
      "ose_profit\030\027 \001(\003\022\023\n\013close_price\030\030 \001(\003\022\021\n" +
      "\tclose_qty\030\031 \001(\r\022A\n\010currency\030\032 \001(\0162/.com" +
      ".demo.model.proto.trade.common.CurrencyT" +
      "ype\"\230\001\n\020QueryHisMatchRsp\0227\n\003ret\030\001 \001(\0132*." +
      "com.demo.model.proto.gateway.TradeRetCod" +
      "e\022\017\n\007account\030\002 \001(\t\022:\n\006matchs\030\003 \003(\0132*.com" +
      ".demo.model.proto.gateway.HisMatchInfo\"\247" +
      "\001\n\023QueryHisPositionReq\022\022\n\nsession_id\030\001 \001" +
      "(\004\022\017\n\007account\030\002 \001(\t\022\014\n\004date\030\003 \001(\t\0226\n\004fla",
      "g\030\004 \001(\0162(.com.demo.model.proto.gateway.S" +
      "ettleFlag\022\020\n\010page_num\030\005 \001(\r\022\023\n\013request_n" +
      "um\030\006 \001(\r\"\236\001\n\023QueryHisPositionRsp\0227\n\003ret\030" +
      "\001 \001(\0132*.com.demo.model.proto.gateway.Tra" +
      "deRetCode\022\017\n\007account\030\002 \001(\t\022=\n\tpositions\030" +
      "\003 \003(\0132*.com.demo.model.proto.gateway.Pos" +
      "itionInfo\"\205\010\n\016InsertOrderReq\022\022\n\nsession_" +
      "id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\022\022\n\ninstr_code\030" +
      "\003 \001(\t\022A\n\010category\030\004 \001(\0162/.com.demo.model" +
      ".proto.trade.common.CategoryType\022?\n\007prod",
      "uct\030\005 \001(\0162..com.demo.model.proto.trade.c" +
      "ommon.ProductType\022A\n\010exchange\030\006 \001(\0162/.co" +
      "m.demo.model.proto.trade.common.Exchange" +
      "Type\022A\n\010currency\030\007 \001(\0162/.com.demo.model." +
      "proto.trade.common.CurrencyType\022\r\n\005price" +
      "\030\010 \001(\003\022\013\n\003vol\030\t \001(\r\022:\n\006direct\030\n \001(\0162*.co" +
      "m.demo.model.proto.gateway.BSDirectType\022" +
      "?\n\norder_type\030\013 \001(\0162+.com.demo.model.pro" +
      "to.gateway.OrderTypeType\022\021\n\tprecision\030\014 " +
      "\001(\r\0228\n\006offset\030\r \001(\0162(.com.demo.model.pro",
      "to.gateway.OffsetType\022:\n\005hedge\030\016 \001(\0162+.c" +
      "om.demo.model.proto.gateway.HedgeFlagTyp" +
      "e\022D\n\rtime_codition\030\017 \001(\0162-.com.demo.mode" +
      "l.proto.gateway.TimeInForceType\022\027\n\017expir" +
      "e_datetime\030\020 \001(\t\022M\n\rvol_cond_type\030\021 \001(\0162" +
      "6.com.demo.model.proto.gateway.MatchVolu" +
      "meConditionType\022L\n\rcon_cond_type\030\022 \001(\01625" +
      ".com.demo.model.proto.gateway.Contingent" +
      "ConditionType\022\026\n\016order_local_id\030\023 \001(\t\022\022\n" +
      "\nstop_price\030\024 \001(\003\022\025\n\rmin_clip_size\030\025 \001(\r",
      "\022\025\n\rmax_clip_size\030\026 \001(\r\022\022\n\nlocal_time\030\027 " +
      "\001(\t\022\020\n\010usr_data\030\030 \001(\004\022\022\n\nis_add_one\030\031 \001(" +
      "\t\"\277\010\n\016InsertOrderRsp\0227\n\003ret\030\001 \001(\0132*.com." +
      "demo.model.proto.gateway.TradeRetCode\022\017\n" +
      "\007account\030\002 \001(\t\022\022\n\ninstr_code\030\003 \001(\t\022A\n\010ca" +
      "tegory\030\004 \001(\0162/.com.demo.model.proto.trad" +
      "e.common.CategoryType\022?\n\007product\030\005 \001(\0162." +
      ".com.demo.model.proto.trade.common.Produ" +
      "ctType\022A\n\010exchange\030\006 \001(\0162/.com.demo.mode" +
      "l.proto.trade.common.ExchangeType\022A\n\010cur",
      "rency\030\007 \001(\0162/.com.demo.model.proto.trade" +
      ".common.CurrencyType\022\r\n\005price\030\010 \001(\003\022\013\n\003v" +
      "ol\030\t \001(\r\022:\n\006direct\030\n \001(\0162*.com.demo.mode" +
      "l.proto.gateway.BSDirectType\022?\n\norder_ty" +
      "pe\030\013 \001(\0162+.com.demo.model.proto.gateway." +
      "OrderTypeType\022\021\n\tprecision\030\014 \001(\r\0228\n\006offs" +
      "et\030\r \001(\0162(.com.demo.model.proto.gateway." +
      "OffsetType\022:\n\005hedge\030\016 \001(\0162+.com.demo.mod" +
      "el.proto.gateway.HedgeFlagType\022D\n\rtime_c" +
      "odition\030\017 \001(\0162-.com.demo.model.proto.gat",
      "eway.TimeInForceType\022\027\n\017expire_datetime\030" +
      "\020 \001(\t\022M\n\rvol_cond_type\030\021 \001(\01626.com.demo." +
      "model.proto.gateway.MatchVolumeCondition" +
      "Type\022L\n\rcon_cond_type\030\022 \001(\01625.com.demo.m" +
      "odel.proto.gateway.ContingentConditionTy" +
      "pe\022\026\n\016order_local_id\030\023 \001(\t\022\022\n\nstop_price" +
      "\030\024 \001(\003\022\025\n\rmin_clip_size\030\025 \001(\r\022\025\n\rmax_cli" +
      "p_size\030\026 \001(\r\022\022\n\nlocal_time\030\027 \001(\t\022\020\n\010usr_" +
      "data\030\030 \001(\004\022\022\n\nis_add_one\030\031 \001(\t\022\023\n\013server" +
      "_flag\030\032 \001(\t\"\\\n\016CancelOrderReq\022\022\n\nsession",
      "_id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\022\020\n\010order_no\030\003" +
      " \001(\t\022\023\n\013server_flag\030\004 \001(\t\"\303\001\n\016CancelOrde" +
      "rRsp\0227\n\003ret\030\001 \001(\0132*.com.demo.model.proto" +
      ".gateway.TradeRetCode\022\017\n\007account\030\002 \001(\t\022\022" +
      "\n\ninstr_code\030\003 \001(\t\022A\n\010exchange\030\004 \001(\0162/.c" +
      "om.demo.model.proto.trade.common.Exchang" +
      "eType\022\020\n\010order_no\030\005 \001(\t\"\205\001\n\013ModOrderReq\022" +
      "\017\n\007account\030\001 \001(\t\022>\n\010orderReq\030\002 \001(\0132,.com" +
      ".demo.model.proto.gateway.InsertOrderReq" +
      "\022\020\n\010order_no\030\003 \001(\t\022\023\n\013server_flag\030\004 \001(\t\"",
      "\277\002\n\013ModOrderRsp\0227\n\003ret\030\001 \001(\0132*.com.demo." +
      "model.proto.gateway.TradeRetCode\022\017\n\007acco" +
      "unt\030\002 \001(\t\022\022\n\ninstr_code\030\003 \001(\t\022A\n\010exchang" +
      "e\030\004 \001(\0162/.com.demo.model.proto.trade.com" +
      "mon.ExchangeType\022\020\n\010order_no\030\005 \001(\t\022\023\n\013or" +
      "der_price\030\006 \001(\003\022\021\n\torder_qty\030\007 \001(\r\022B\n\013or" +
      "der_state\030\010 \001(\0162-.com.demo.model.proto.g" +
      "ateway.OrderStatusType\022\021\n\tprecision\030\t \001(" +
      "\r\"\230\001\n\016PositionProfit\022\017\n\007account\030\001 \001(\t\022\022\n" +
      "\ninstr_code\030\002 \001(\t\022\021\n\tprecision\030\003 \001(\r\022\023\n\013",
      "position_id\030\004 \001(\t\022\032\n\022position_stream_id\030" +
      "\005 \001(\r\022\016\n\006profit\030\006 \001(\003\022\r\n\005price\030\007 \001(\003\"\232\001\n" +
      "\017PositionProfits\0227\n\003ret\030\001 \001(\0132*.com.demo" +
      ".model.proto.gateway.TradeRetCode\022\017\n\007acc" +
      "ount\030\002 \001(\t\022=\n\007profits\030\003 \003(\0132,.com.demo.m" +
      "odel.proto.gateway.PositionProfit\"V\n\021Acc" +
      "ountDisConnect\022\017\n\007account\030\001 \001(\t\022\025\n\ris_di" +
      "sconnect\030\002 \001(\010\022\031\n\021disconn_date_time\030\003 \001(" +
      "\004\"\364\001\n\013QueryFeeReq\022\022\n\nsession_id\030\001 \001(\004\022\017\n" +
      "\007account\030\003 \001(\t\022A\n\010exchange\030\004 \001(\0162/.com.d",
      "emo.model.proto.trade.common.ExchangeTyp" +
      "e\022\022\n\ninstr_code\030\005 \001(\t\022\021\n\tprecision\030\006 \001(\r" +
      "\022\r\n\005price\030\007 \001(\003\022\013\n\003qty\030\010 \001(\004\022:\n\006direct\030\t" +
      " \001(\0162*.com.demo.model.proto.gateway.BSDi" +
      "rectType\"\331\001\n\013QueryFeeRsp\022\017\n\007account\030\003 \001(" +
      "\t\022A\n\010exchange\030\004 \001(\0162/.com.demo.model.pro" +
      "to.trade.common.ExchangeType\022\022\n\ninstr_co" +
      "de\030\005 \001(\t\022\016\n\006charge\030\006 \001(\004\022\014\n\004name\030\007 \001(\t\022\013" +
      "\n\003amt\030\010 \001(\004\0227\n\003ret\030\t \001(\0132*.com.demo.mode" +
      "l.proto.gateway.TradeRetCode\"8\n\021QueryCom",
      "modityReq\022\022\n\nsession_id\030\001 \001(\004\022\017\n\007account" +
      "\030\002 \001(\t\"\354\004\n\rCommodityInfo\022\020\n\010exchange\030\001 \001" +
      "(\t\022A\n\010category\030\002 \001(\0162/.com.demo.model.pr" +
      "oto.trade.common.CategoryType\022\021\n\tcommodi" +
      "ty\030\003 \001(\t\022\026\n\016commodity_name\030\004 \001(\t\022\032\n\022comm" +
      "odity_eng_name\030\005 \001(\t\022\026\n\016trade_currency\030\006" +
      " \001(\t\022\025\n\rcontract_size\030\007 \001(\001\022I\n\017open_clos" +
      "e_mode\030\010 \001(\01620.com.demo.model.proto.trad" +
      "e.common.OpenCloseType\022\032\n\022strike_price_t" +
      "imes\030\t \001(\001\022\033\n\023commodity_tick_size\030\n \001(\001\022",
      "\035\n\025commodity_denominator\030\013 \001(\005\022D\n\ncmb_di" +
      "rect\030\014 \001(\01620.com.demo.model.proto.trade." +
      "common.CmbDirectType\022I\n\rdelivery_mode\030\r " +
      "\001(\01622.com.demo.model.proto.trade.common." +
      "DeliverModeType\022\025\n\rdelivery_days\030\016 \001(\005\022\024" +
      "\n\014add_one_time\030\017 \001(\t\022\033\n\023commodity_time_z" +
      "one\030\020 \001(\005\022\022\n\nis_add_one\030\021 \001(\010\"\237\001\n\022QueryC" +
      "ommodityRsps\0227\n\003ret\030\001 \001(\0132*.com.demo.mod" +
      "el.proto.gateway.TradeRetCode\022\017\n\007account" +
      "\030\002 \001(\t\022?\n\ncommoditys\030\003 \003(\0132+.com.demo.mo",
      "del.proto.gateway.CommodityInfo\"\320\001\n\020Quer" +
      "yContractReq\022\022\n\nsession_id\030\001 \001(\004\022A\n\010exch" +
      "ange\030\002 \001(\0162/.com.demo.model.proto.trade." +
      "common.ExchangeType\022A\n\010category\030\003 \001(\0162/." +
      "com.demo.model.proto.trade.common.Catego" +
      "ryType\022\021\n\tcommodity\030\004 \001(\t\022\017\n\007account\030\005 \001" +
      "(\t\"\252\004\n\014ContractInfo\022\020\n\010exchange\030\001 \001(\t\022A\n" +
      "\010category\030\002 \001(\0162/.com.demo.model.proto.t" +
      "rade.common.CategoryType\022\021\n\tcommodity\030\003 " +
      "\001(\t\022\020\n\010contract\030\004 \001(\t\022\024\n\014strile_price\030\005 ",
      "\001(\t\022F\n\016call_put_flag1\030\006 \001(\0162..com.demo.m" +
      "odel.proto.trade.common.CallPutType\022\021\n\tc" +
      "ontract2\030\007 \001(\t\022\025\n\rstrile_price2\030\010 \001(\t\022F\n" +
      "\016call_put_flag2\030\t \001(\0162..com.demo.model.p" +
      "roto.trade.common.CallPutType\022F\n\rcontrac" +
      "t_type\030\n \001(\0162/.com.demo.model.proto.trad" +
      "e.common.ContractType\022!\n\031quote_underlyin" +
      "g_contract\030\013 \001(\t\022\025\n\rcontract_name\030\014 \001(\t\022" +
      "\031\n\021contract_exp_date\030\r \001(\t\022\027\n\017last_trade" +
      "_date\030\016 \001(\t\022\032\n\022firtst_notice_date\030\017 \001(\t\"",
      "\234\001\n\021QueryContractRsps\0227\n\003ret\030\001 \001(\0132*.com" +
      ".demo.model.proto.gateway.TradeRetCode\022\017" +
      "\n\007account\030\002 \001(\t\022=\n\tcontracts\030\003 \003(\0132*.com" +
      ".demo.model.proto.gateway.ContractInfo\"7" +
      "\n\020QueryCurrencyReq\022\022\n\nsession_id\030\001 \001(\004\022\017" +
      "\n\007account\030\002 \001(\t\"\356\001\n\014CurrencyInfo\022D\n\013curr" +
      "ency_no\030\001 \001(\0162/.com.demo.model.proto.tra" +
      "de.common.CurrencyType\022J\n\021currency_group" +
      "_no\030\002 \001(\0162/.com.demo.model.proto.trade.c" +
      "ommon.CurrencyType\022\033\n\023currency_trade_rat",
      "e\030\003 \001(\004\022\034\n\024currency_trade_rate2\030\004 \001(\004\022\021\n" +
      "\tprecision\030\005 \001(\r\"\234\001\n\021QueryCurrencyRsps\0227" +
      "\n\003ret\030\001 \001(\0132*.com.demo.model.proto.gatew" +
      "ay.TradeRetCode\022\017\n\007account\030\002 \001(\t\022=\n\tcurr" +
      "encys\030\003 \003(\0132*.com.demo.model.proto.gatew" +
      "ay.CurrencyInfo\"7\n\020QueryExchangeReq\022\022\n\ns" +
      "ession_id\030\001 \001(\004\022\017\n\007account\030\002 \001(\t\"k\n\014Exch" +
      "angeInfo\022D\n\013exchange_no\030\001 \001(\0162/.com.demo" +
      ".model.proto.trade.common.ExchangeType\022\025" +
      "\n\rexchange_name\030\002 \001(\t\"\234\001\n\021QueryExchangeR",
      "sps\0227\n\003ret\030\001 \001(\0132*.com.demo.model.proto." +
      "gateway.TradeRetCode\022\017\n\007account\030\002 \001(\t\022=\n" +
      "\texchanges\030\003 \003(\0132*.com.demo.model.proto." +
      "gateway.ExchangeInfo\"h\n\013ContactInfo\0227\n\003r" +
      "et\030\001 \001(\0132*.com.demo.model.proto.gateway." +
      "TradeRetCode\022\017\n\007account\030\002 \001(\t\022\017\n\007contact" +
      "\030\003 \003(\t\"6\n\022VertificateCodeReq\022\017\n\007account\030" +
      "\001 \001(\t\022\017\n\007contact\030\002 \001(\t\"\211\001\n\022VertificateCo" +
      "deRsp\0227\n\003ret\030\001 \001(\0132*.com.demo.model.prot" +
      "o.gateway.TradeRetCode\022\017\n\007account\030\002 \001(\t\022",
      "\026\n\016secondSerialID\030\003 \001(\t\022\021\n\teffective\030\004 \001" +
      "(\r\"A\n\025SetVertificateCodeReq\022\017\n\007account\030\001" +
      " \001(\t\022\027\n\017vertificateCode\030\002 \001(\t*,\n\014ProtoVe" +
      "rsion\022\r\n\tVERSION_0\020\000\022\r\n\tVERSION_1\020\001B\002P\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.demo.model.proto.trade.common.TradeCommonTypeDef.getDescriptor(),
          TradeTypeDef.getDescriptor(),
        }, assigner);
    internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_descriptor,
        new String[] { "SeriesId", "Type", "Version", "Ret", "Data", "Platform", "DeviceId", });
    internal_static_com_demo_model_proto_gateway_AccountInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_model_proto_gateway_AccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_AccountInfo_descriptor,
        new String[] { "Account", });
    internal_static_com_demo_model_proto_gateway_TradeRetCode_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_demo_model_proto_gateway_TradeRetCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_TradeRetCode_descriptor,
        new String[] { "Code", "Msg", });
    internal_static_com_demo_model_proto_gateway_AccountHeartBeatReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_demo_model_proto_gateway_AccountHeartBeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_AccountHeartBeatReq_descriptor,
        new String[] { "SessionId", "Account", });
    internal_static_com_demo_model_proto_gateway_AccountHearBeatRsp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_demo_model_proto_gateway_AccountHearBeatRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_AccountHearBeatRsp_descriptor,
        new String[] { "Ret", "Account", });
    internal_static_com_demo_model_proto_gateway_UsrLoginReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_demo_model_proto_gateway_UsrLoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_UsrLoginReq_descriptor,
        new String[] { "Account", "Pwd", "NewPwd", "IpAddress", "ChangePwd", });
    internal_static_com_demo_model_proto_gateway_UsrLoginRsp_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_demo_model_proto_gateway_UsrLoginRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_UsrLoginRsp_descriptor,
        new String[] { "Ret", "SessionId", "Account", "LastLoginIp", "LastLoginTime", "LastLogoutTime", "IsNeedModPwd", "TradeDate", "LastSettleTime", "Contact", });
    internal_static_com_demo_model_proto_gateway_APIReadyRtn_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_demo_model_proto_gateway_APIReadyRtn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_APIReadyRtn_descriptor,
        new String[] { "Ret", "Account", });
    internal_static_com_demo_model_proto_gateway_UsrLogoutReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_demo_model_proto_gateway_UsrLogoutReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_UsrLogoutReq_descriptor,
        new String[] { "SessionId", "Account", "Site", });
    internal_static_com_demo_model_proto_gateway_UsrLogoutRsp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_demo_model_proto_gateway_UsrLogoutRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_UsrLogoutRsp_descriptor,
        new String[] { "Ret", "Account", });
    internal_static_com_demo_model_proto_gateway_ModPassWordReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_demo_model_proto_gateway_ModPassWordReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_ModPassWordReq_descriptor,
        new String[] { "SessionId", "Account", "OldPwd", "NewPwd", });
    internal_static_com_demo_model_proto_gateway_ModPassWordRsp_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_demo_model_proto_gateway_ModPassWordRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_ModPassWordRsp_descriptor,
        new String[] { "Ret", "Account", });
    internal_static_com_demo_model_proto_gateway_QueryLoginStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_demo_model_proto_gateway_QueryLoginStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryLoginStatusReq_descriptor,
        new String[] { "SessionId", "Account", });
    internal_static_com_demo_model_proto_gateway_QueryLoginStatusRsp_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_demo_model_proto_gateway_QueryLoginStatusRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryLoginStatusRsp_descriptor,
        new String[] { "Ret", "Account", "IsDisconnect", });
    internal_static_com_demo_model_proto_gateway_QueryFutureBalanceReq_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_demo_model_proto_gateway_QueryFutureBalanceReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryFutureBalanceReq_descriptor,
        new String[] { "SessionId", "Account", });
    internal_static_com_demo_model_proto_gateway_FutureBalance_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_demo_model_proto_gateway_FutureBalance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_FutureBalance_descriptor,
        new String[] { "Account", "Name", "Precision", "Currency", "PreBalance", "PreUnexpProfit", "PreLmePositionProfit", "PreEquity", "PreAvailable", "PreMaketEquity", "Available", "WithDraw", "AdjustValue", "Pledged", "Commission", "Fee", "AccountFee", "BuyFreeze", "BuyFreezeMargin", "FreezeFee", "SellFreeze", "SellFreezeMargin", "CloseProfit", "UnexpProfit", "ExpProfit", "PositionProfit", "LmePositionProfit", "InitialMargin", "MaintenanceMargin", "UpperInitalMargin", "UpperMaintenanceMargin", "Discount", "Deposit", "Drawing", "SwapInValue", "SwapOutValue", "PremiumIncome", "PremiumPay", "Balance", "Equity", "MarketEquity", "AuthValue", "ExchangeRate", });
    internal_static_com_demo_model_proto_gateway_QueryFutureBalanceRsp_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_demo_model_proto_gateway_QueryFutureBalanceRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryFutureBalanceRsp_descriptor,
        new String[] { "Ret", "Account", "SumBalance", "Balances", });
    internal_static_com_demo_model_proto_gateway_QueryOrderReq_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_demo_model_proto_gateway_QueryOrderReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryOrderReq_descriptor,
        new String[] { "SessionId", "Account", "Exchange", "InstrCode", "Direct", "Category", "Product", "OrderType", "TimeInForce", "Hedge", "ReqId", "ExchangeOrderId", "ServerFlag", "ExpireTime", "IsRisk", });
    internal_static_com_demo_model_proto_gateway_FutureOrderInfo_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_demo_model_proto_gateway_FutureOrderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_FutureOrderInfo_descriptor,
        new String[] { "Account", "Exchange", "InstrCode", "Direct", "Category", "Product", "Precision", "OrderType", "TimeInForce", "ExpireTime", "IsRisk", "PositionEffect", "Hedge", "Price", "MatchPrice", "StopPrice", "Vol", "State", "AveragePrice", "MatchQty", "OrderNo", "MinClipSize", "MaxClipSize", "CalcelQty", "OrderStreamId", "UpperNo", "UpperChannelNo", "LocalNo", "UpperStreamNo", "IsAddOne", "UsrData", "SystemNo", "ExchangeSystemNo", "ParentSystemNo", "InsertTime", "UpdateTime", "ServerFlag", "ErrorCode", "ErrorText", "Ret", });
    internal_static_com_demo_model_proto_gateway_QueryOrderRsp_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_demo_model_proto_gateway_QueryOrderRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryOrderRsp_descriptor,
        new String[] { "Ret", "Account", "Orders", });
    internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentReq_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentReq_descriptor,
        new String[] { "SessionId", "Account", });
    internal_static_com_demo_model_proto_gateway_AccountFeeRent_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_demo_model_proto_gateway_AccountFeeRent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_AccountFeeRent_descriptor,
        new String[] { "Account", "Exchange", "ProductCode", "Category", "Type", "Currency", "CurrencyGroupNo", "OpenCloseFee", "CloseTodayFee", "Precision", });
    internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentRsp_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryAccountFeeRentRsp_descriptor,
        new String[] { "Ret", "Account", "FeeInfo", });
    internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentReq_descriptor,
        new String[] { "SessionId", "Account", "Exchange", "ProductCode", "Category", });
    internal_static_com_demo_model_proto_gateway_AccountMarginRentInfo_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_demo_model_proto_gateway_AccountMarginRentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_AccountMarginRentInfo_descriptor,
        new String[] { "Account", "Exchange", "ProductCode", "Category", "InstrCode", "Currency", "Type", "InitialMargin", "MaintenanceMargin", "SellInitMargin", "SellMainMargin", "LockMargin", "Precision", });
    internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentRsp_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryAccountMarginRentRsp_descriptor,
        new String[] { "Ret", "Account", "MarginInfos", });
    internal_static_com_demo_model_proto_gateway_QueryPositionSummaryReq_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_demo_model_proto_gateway_QueryPositionSummaryReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryPositionSummaryReq_descriptor,
        new String[] { "SessionId", "Account", "Exchange", "InstrCode", "PageNum", "RequestNum", });
    internal_static_com_demo_model_proto_gateway_PositionInfo_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_demo_model_proto_gateway_PositionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_PositionInfo_descriptor,
        new String[] { "Account", "Exchange", "InstrCode", "Currency", "Precision", "Position", "PositionPrice", "Average", "OpenCost", "PositionProfit", "LmePositionProfit", "CalculatePrice", "InitialMargin", "MaintenanceMargin", "UpperInitalMargin", "UpperMaintenanceMargin", "PosType", "PreMargin", "UsedMargin", "Direct", "Hedge", "PositionNo", "ServerFlag", "OrderNo", "MatchId", "UpperNo", "PositionStreamNo", "LocalTime", });
    internal_static_com_demo_model_proto_gateway_QueryPositionSummaryRsp_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_demo_model_proto_gateway_QueryPositionSummaryRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryPositionSummaryRsp_descriptor,
        new String[] { "Ret", "Account", "Positions", });
    internal_static_com_demo_model_proto_gateway_QueryPositionReq_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_demo_model_proto_gateway_QueryPositionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryPositionReq_descriptor,
        new String[] { "SessionId", "Account", "Exchange", "InstrCode", "PageNum", "RequestNum", });
    internal_static_com_demo_model_proto_gateway_QueryPositionRsp_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_demo_model_proto_gateway_QueryPositionRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryPositionRsp_descriptor,
        new String[] { "Ret", "Account", "Positions", });
    internal_static_com_demo_model_proto_gateway_QueryMatchReq_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_demo_model_proto_gateway_QueryMatchReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryMatchReq_descriptor,
        new String[] { "SessionId", "Account", "Exchange", "InstrCode", "Category", "Product", "Direct", "PositionEffect", "UpperNo", "ExchangeNo", "IsAddOne", "ServerFlag", });
    internal_static_com_demo_model_proto_gateway_MatchInfo_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_demo_model_proto_gateway_MatchInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_MatchInfo_descriptor,
        new String[] { "Account", "InstrCode", "Exchange", "Currency", "Category", "Product", "Precision", "Direct", "Offset", "Date", "Vol", "Price", "ServerFlag", "OrderNo", "OrderSystemNo", "MatchNo", "UpperMatchNo", "ExchageMatchNo", "MatchDataTime", "UpperMatchDatetime", "UpperNo", "OrderLocalId", "ExchangeOrderNo", "IsAddOne", "Commission", "ClosePosPrice", });
    internal_static_com_demo_model_proto_gateway_QueryMatchRsp_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_demo_model_proto_gateway_QueryMatchRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryMatchRsp_descriptor,
        new String[] { "Ret", "Account", "Matchs", });
    internal_static_com_demo_model_proto_gateway_QueryHisOrderReq_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_demo_model_proto_gateway_QueryHisOrderReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryHisOrderReq_descriptor,
        new String[] { "SessionId", "Account", "BeginDate", "EndDate", });
    internal_static_com_demo_model_proto_gateway_HisOrderInfo_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_com_demo_model_proto_gateway_HisOrderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_HisOrderInfo_descriptor,
        new String[] { "Date", "Account", "InstrCode", "Category", "Exchange", "Precision", "StrikePrice", "OrderType", "TimeInForce", "ExpireTime", "IsRiskOrder", "OrderSide", "PositionEffect", "HedgeFlag", "OrderPrice", "StopPrice", "OrderQty", "OrderMinQty", "OrderCanceledQty", "ServerFlag", "OrderNo", "OrderInsertTime", "OrderUpdateTime", "OrderStatusType", "MatchPrice", "MatchQty", "IsAddOne", "AddOneIsValid", "ErrorCode", "ErrorText", });
    internal_static_com_demo_model_proto_gateway_QueryHisOrderRsp_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_com_demo_model_proto_gateway_QueryHisOrderRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryHisOrderRsp_descriptor,
        new String[] { "Ret", "Account", "Orders", });
    internal_static_com_demo_model_proto_gateway_QueryHisMatchReq_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_com_demo_model_proto_gateway_QueryHisMatchReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryHisMatchReq_descriptor,
        new String[] { "SessionId", "Account", "BeginDate", "EndDate", });
    internal_static_com_demo_model_proto_gateway_HisMatchInfo_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_com_demo_model_proto_gateway_HisMatchInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_HisMatchInfo_descriptor,
        new String[] { "TradeDate", "Account", "InstrCode", "Category", "Exchange", "Precision", "StrikePrice", "MatchSide", "PositionEffect", "HedgeFlag", "ServerFlag", "OrderNo", "MatchPrice", "MatchQty", "SettleDate", "MatchNo", "Turnover", "PremiumIncome", "PremiumPay", "AccountFee", "MatchDateTime", "UpperMatchDateTime", "CloseProfit", "ClosePrice", "CloseQty", "Currency", });
    internal_static_com_demo_model_proto_gateway_QueryHisMatchRsp_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_com_demo_model_proto_gateway_QueryHisMatchRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryHisMatchRsp_descriptor,
        new String[] { "Ret", "Account", "Matchs", });
    internal_static_com_demo_model_proto_gateway_QueryHisPositionReq_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_com_demo_model_proto_gateway_QueryHisPositionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryHisPositionReq_descriptor,
        new String[] { "SessionId", "Account", "Date", "Flag", "PageNum", "RequestNum", });
    internal_static_com_demo_model_proto_gateway_QueryHisPositionRsp_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_com_demo_model_proto_gateway_QueryHisPositionRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryHisPositionRsp_descriptor,
        new String[] { "Ret", "Account", "Positions", });
    internal_static_com_demo_model_proto_gateway_InsertOrderReq_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_com_demo_model_proto_gateway_InsertOrderReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_InsertOrderReq_descriptor,
        new String[] { "SessionId", "Account", "InstrCode", "Category", "Product", "Exchange", "Currency", "Price", "Vol", "Direct", "OrderType", "Precision", "Offset", "Hedge", "TimeCodition", "ExpireDatetime", "VolCondType", "ConCondType", "OrderLocalId", "StopPrice", "MinClipSize", "MaxClipSize", "LocalTime", "UsrData", "IsAddOne", });
    internal_static_com_demo_model_proto_gateway_InsertOrderRsp_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_com_demo_model_proto_gateway_InsertOrderRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_InsertOrderRsp_descriptor,
        new String[] { "Ret", "Account", "InstrCode", "Category", "Product", "Exchange", "Currency", "Price", "Vol", "Direct", "OrderType", "Precision", "Offset", "Hedge", "TimeCodition", "ExpireDatetime", "VolCondType", "ConCondType", "OrderLocalId", "StopPrice", "MinClipSize", "MaxClipSize", "LocalTime", "UsrData", "IsAddOne", "ServerFlag", });
    internal_static_com_demo_model_proto_gateway_CancelOrderReq_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_com_demo_model_proto_gateway_CancelOrderReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_CancelOrderReq_descriptor,
        new String[] { "SessionId", "Account", "OrderNo", "ServerFlag", });
    internal_static_com_demo_model_proto_gateway_CancelOrderRsp_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_com_demo_model_proto_gateway_CancelOrderRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_CancelOrderRsp_descriptor,
        new String[] { "Ret", "Account", "InstrCode", "Exchange", "OrderNo", });
    internal_static_com_demo_model_proto_gateway_ModOrderReq_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_com_demo_model_proto_gateway_ModOrderReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_ModOrderReq_descriptor,
        new String[] { "Account", "OrderReq", "OrderNo", "ServerFlag", });
    internal_static_com_demo_model_proto_gateway_ModOrderRsp_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_com_demo_model_proto_gateway_ModOrderRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_ModOrderRsp_descriptor,
        new String[] { "Ret", "Account", "InstrCode", "Exchange", "OrderNo", "OrderPrice", "OrderQty", "OrderState", "Precision", });
    internal_static_com_demo_model_proto_gateway_PositionProfit_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_com_demo_model_proto_gateway_PositionProfit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_PositionProfit_descriptor,
        new String[] { "Account", "InstrCode", "Precision", "PositionId", "PositionStreamId", "Profit", "Price", });
    internal_static_com_demo_model_proto_gateway_PositionProfits_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_com_demo_model_proto_gateway_PositionProfits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_PositionProfits_descriptor,
        new String[] { "Ret", "Account", "Profits", });
    internal_static_com_demo_model_proto_gateway_AccountDisConnect_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_com_demo_model_proto_gateway_AccountDisConnect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_AccountDisConnect_descriptor,
        new String[] { "Account", "IsDisconnect", "DisconnDateTime", });
    internal_static_com_demo_model_proto_gateway_QueryFeeReq_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_com_demo_model_proto_gateway_QueryFeeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryFeeReq_descriptor,
        new String[] { "SessionId", "Account", "Exchange", "InstrCode", "Precision", "Price", "Qty", "Direct", });
    internal_static_com_demo_model_proto_gateway_QueryFeeRsp_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_com_demo_model_proto_gateway_QueryFeeRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryFeeRsp_descriptor,
        new String[] { "Account", "Exchange", "InstrCode", "Charge", "Name", "Amt", "Ret", });
    internal_static_com_demo_model_proto_gateway_QueryCommodityReq_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_com_demo_model_proto_gateway_QueryCommodityReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryCommodityReq_descriptor,
        new String[] { "SessionId", "Account", });
    internal_static_com_demo_model_proto_gateway_CommodityInfo_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_com_demo_model_proto_gateway_CommodityInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_CommodityInfo_descriptor,
        new String[] { "Exchange", "Category", "Commodity", "CommodityName", "CommodityEngName", "TradeCurrency", "ContractSize", "OpenCloseMode", "StrikePriceTimes", "CommodityTickSize", "CommodityDenominator", "CmbDirect", "DeliveryMode", "DeliveryDays", "AddOneTime", "CommodityTimeZone", "IsAddOne", });
    internal_static_com_demo_model_proto_gateway_QueryCommodityRsps_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_com_demo_model_proto_gateway_QueryCommodityRsps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryCommodityRsps_descriptor,
        new String[] { "Ret", "Account", "Commoditys", });
    internal_static_com_demo_model_proto_gateway_QueryContractReq_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_com_demo_model_proto_gateway_QueryContractReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryContractReq_descriptor,
        new String[] { "SessionId", "Exchange", "Category", "Commodity", "Account", });
    internal_static_com_demo_model_proto_gateway_ContractInfo_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_com_demo_model_proto_gateway_ContractInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_ContractInfo_descriptor,
        new String[] { "Exchange", "Category", "Commodity", "Contract", "StrilePrice", "CallPutFlag1", "Contract2", "StrilePrice2", "CallPutFlag2", "ContractType", "QuoteUnderlyingContract", "ContractName", "ContractExpDate", "LastTradeDate", "FirtstNoticeDate", });
    internal_static_com_demo_model_proto_gateway_QueryContractRsps_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_com_demo_model_proto_gateway_QueryContractRsps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryContractRsps_descriptor,
        new String[] { "Ret", "Account", "Contracts", });
    internal_static_com_demo_model_proto_gateway_QueryCurrencyReq_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_com_demo_model_proto_gateway_QueryCurrencyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryCurrencyReq_descriptor,
        new String[] { "SessionId", "Account", });
    internal_static_com_demo_model_proto_gateway_CurrencyInfo_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_com_demo_model_proto_gateway_CurrencyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_CurrencyInfo_descriptor,
        new String[] { "CurrencyNo", "CurrencyGroupNo", "CurrencyTradeRate", "CurrencyTradeRate2", "Precision", });
    internal_static_com_demo_model_proto_gateway_QueryCurrencyRsps_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_com_demo_model_proto_gateway_QueryCurrencyRsps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryCurrencyRsps_descriptor,
        new String[] { "Ret", "Account", "Currencys", });
    internal_static_com_demo_model_proto_gateway_QueryExchangeReq_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_com_demo_model_proto_gateway_QueryExchangeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryExchangeReq_descriptor,
        new String[] { "SessionId", "Account", });
    internal_static_com_demo_model_proto_gateway_ExchangeInfo_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_com_demo_model_proto_gateway_ExchangeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_ExchangeInfo_descriptor,
        new String[] { "ExchangeNo", "ExchangeName", });
    internal_static_com_demo_model_proto_gateway_QueryExchangeRsps_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_com_demo_model_proto_gateway_QueryExchangeRsps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_QueryExchangeRsps_descriptor,
        new String[] { "Ret", "Account", "Exchanges", });
    internal_static_com_demo_model_proto_gateway_ContactInfo_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_com_demo_model_proto_gateway_ContactInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_ContactInfo_descriptor,
        new String[] { "Ret", "Account", "Contact", });
    internal_static_com_demo_model_proto_gateway_VertificateCodeReq_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_com_demo_model_proto_gateway_VertificateCodeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_VertificateCodeReq_descriptor,
        new String[] { "Account", "Contact", });
    internal_static_com_demo_model_proto_gateway_VertificateCodeRsp_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_com_demo_model_proto_gateway_VertificateCodeRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_VertificateCodeRsp_descriptor,
        new String[] { "Ret", "Account", "SecondSerialID", "Effective", });
    internal_static_com_demo_model_proto_gateway_SetVertificateCodeReq_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_com_demo_model_proto_gateway_SetVertificateCodeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_gateway_SetVertificateCodeReq_descriptor,
        new String[] { "Account", "VertificateCode", });
    com.demo.model.proto.trade.common.TradeCommonTypeDef.getDescriptor();
    TradeTypeDef.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
