// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_msg_def.proto

package com.demo.model.proto.gateway;

/**
 * Protobuf type {@code com.demo.model.proto.gateway.TradeMsgCarrier}
 */
public  final class TradeMsgCarrier extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.demo.model.proto.gateway.TradeMsgCarrier)
    TradeMsgCarrierOrBuilder {
  // Use TradeMsgCarrier.newBuilder() to construct.
  private TradeMsgCarrier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TradeMsgCarrier() {
    seriesId_ = 0L;
    type_ = 0;
    version_ = 0;
    data_ = com.google.protobuf.ByteString.EMPTY;
    platform_ = "";
    deviceId_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TradeMsgCarrier(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            seriesId_ = input.readUInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            version_ = rawValue;
            break;
          }
          case 34: {
            TradeRetCode.Builder subBuilder = null;
            if (ret_ != null) {
              subBuilder = ret_.toBuilder();
            }
            ret_ = input.readMessage(TradeRetCode.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ret_);
              ret_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {

            data_ = input.readBytes();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            platform_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TradeMsgDef.internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TradeMsgDef.internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TradeMsgCarrier.class, Builder.class);
  }

  public static final int SERIES_ID_FIELD_NUMBER = 1;
  private long seriesId_;
  /**
   * <pre>
   * 序号(中台使用)
   * </pre>
   *
   * <code>optional uint64 series_id = 1;</code>
   */
  public long getSeriesId() {
    return seriesId_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <pre>
   * 交易消息类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.TradeMsgType type = 2;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 交易消息类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.TradeMsgType type = 2;</code>
   */
  public TradeMsgType getType() {
    TradeMsgType result = TradeMsgType.valueOf(type_);
    return result == null ? TradeMsgType.UNRECOGNIZED : result;
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  private int version_;
  /**
   * <pre>
   * 协议版本号
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.ProtoVersion version = 3;</code>
   */
  public int getVersionValue() {
    return version_;
  }
  /**
   * <pre>
   * 协议版本号
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.ProtoVersion version = 3;</code>
   */
  public ProtoVersion getVersion() {
    ProtoVersion result = ProtoVersion.valueOf(version_);
    return result == null ? ProtoVersion.UNRECOGNIZED : result;
  }

  public static final int RET_FIELD_NUMBER = 4;
  private TradeRetCode ret_;
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
   */
  public boolean hasRet() {
    return ret_ != null;
  }
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
   */
  public TradeRetCode getRet() {
    return ret_ == null ? TradeRetCode.getDefaultInstance() : ret_;
  }
  /**
   * <pre>
   * 错误信息
   * </pre>
   *
   * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
   */
  public TradeRetCodeOrBuilder getRetOrBuilder() {
    return getRet();
  }

  public static final int DATA_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString data_;
  /**
   * <pre>
   * 交易协议数据
   * </pre>
   *
   * <code>optional bytes data = 5;</code>
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int PLATFORM_FIELD_NUMBER = 6;
  private volatile Object platform_;
  /**
   * <pre>
   * 平台 IOS Android PC 
   * </pre>
   *
   * <code>optional string platform = 6;</code>
   */
  public String getPlatform() {
    Object ref = platform_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      platform_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 平台 IOS Android PC 
   * </pre>
   *
   * <code>optional string platform = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    Object ref = platform_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      platform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 7;
  private volatile Object deviceId_;
  /**
   * <pre>
   * 设备ID 
   * </pre>
   *
   * <code>optional string device_id = 7;</code>
   */
  public String getDeviceId() {
    Object ref = deviceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备ID 
   * </pre>
   *
   * <code>optional string device_id = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    Object ref = deviceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (seriesId_ != 0L) {
      output.writeUInt64(1, seriesId_);
    }
    if (type_ != TradeMsgType.UNKNOWN_MSG.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (version_ != ProtoVersion.VERSION_0.getNumber()) {
      output.writeEnum(3, version_);
    }
    if (ret_ != null) {
      output.writeMessage(4, getRet());
    }
    if (!data_.isEmpty()) {
      output.writeBytes(5, data_);
    }
    if (!getPlatformBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, platform_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, deviceId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (seriesId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, seriesId_);
    }
    if (type_ != TradeMsgType.UNKNOWN_MSG.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (version_ != ProtoVersion.VERSION_0.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, version_);
    }
    if (ret_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRet());
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, data_);
    }
    if (!getPlatformBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, platform_);
    }
    if (!getDeviceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, deviceId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TradeMsgCarrier)) {
      return super.equals(obj);
    }
    TradeMsgCarrier other = (TradeMsgCarrier) obj;

    boolean result = true;
    result = result && (getSeriesId()
        == other.getSeriesId());
    result = result && type_ == other.type_;
    result = result && version_ == other.version_;
    result = result && (hasRet() == other.hasRet());
    if (hasRet()) {
      result = result && getRet()
          .equals(other.getRet());
    }
    result = result && getData()
        .equals(other.getData());
    result = result && getPlatform()
        .equals(other.getPlatform());
    result = result && getDeviceId()
        .equals(other.getDeviceId());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SERIES_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeriesId());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + version_;
    if (hasRet()) {
      hash = (37 * hash) + RET_FIELD_NUMBER;
      hash = (53 * hash) + getRet().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getPlatform().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TradeMsgCarrier parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeMsgCarrier parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeMsgCarrier parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TradeMsgCarrier parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TradeMsgCarrier parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TradeMsgCarrier parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TradeMsgCarrier parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TradeMsgCarrier parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TradeMsgCarrier parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TradeMsgCarrier parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TradeMsgCarrier prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.demo.model.proto.gateway.TradeMsgCarrier}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.demo.model.proto.gateway.TradeMsgCarrier)
      TradeMsgCarrierOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TradeMsgCarrier.class, Builder.class);
    }

    // Construct using com.demo.model.proto.gateway.TradeMsgCarrier.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      seriesId_ = 0L;

      type_ = 0;

      version_ = 0;

      if (retBuilder_ == null) {
        ret_ = null;
      } else {
        ret_ = null;
        retBuilder_ = null;
      }
      data_ = com.google.protobuf.ByteString.EMPTY;

      platform_ = "";

      deviceId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TradeMsgDef.internal_static_com_demo_model_proto_gateway_TradeMsgCarrier_descriptor;
    }

    public TradeMsgCarrier getDefaultInstanceForType() {
      return TradeMsgCarrier.getDefaultInstance();
    }

    public TradeMsgCarrier build() {
      TradeMsgCarrier result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public TradeMsgCarrier buildPartial() {
      TradeMsgCarrier result = new TradeMsgCarrier(this);
      result.seriesId_ = seriesId_;
      result.type_ = type_;
      result.version_ = version_;
      if (retBuilder_ == null) {
        result.ret_ = ret_;
      } else {
        result.ret_ = retBuilder_.build();
      }
      result.data_ = data_;
      result.platform_ = platform_;
      result.deviceId_ = deviceId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TradeMsgCarrier) {
        return mergeFrom((TradeMsgCarrier)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TradeMsgCarrier other) {
      if (other == TradeMsgCarrier.getDefaultInstance()) return this;
      if (other.getSeriesId() != 0L) {
        setSeriesId(other.getSeriesId());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.version_ != 0) {
        setVersionValue(other.getVersionValue());
      }
      if (other.hasRet()) {
        mergeRet(other.getRet());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (!other.getPlatform().isEmpty()) {
        platform_ = other.platform_;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TradeMsgCarrier parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TradeMsgCarrier) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long seriesId_ ;
    /**
     * <pre>
     * 序号(中台使用)
     * </pre>
     *
     * <code>optional uint64 series_id = 1;</code>
     */
    public long getSeriesId() {
      return seriesId_;
    }
    /**
     * <pre>
     * 序号(中台使用)
     * </pre>
     *
     * <code>optional uint64 series_id = 1;</code>
     */
    public Builder setSeriesId(long value) {
      
      seriesId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 序号(中台使用)
     * </pre>
     *
     * <code>optional uint64 series_id = 1;</code>
     */
    public Builder clearSeriesId() {
      
      seriesId_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 交易消息类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeMsgType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 交易消息类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeMsgType type = 2;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易消息类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeMsgType type = 2;</code>
     */
    public TradeMsgType getType() {
      TradeMsgType result = TradeMsgType.valueOf(type_);
      return result == null ? TradeMsgType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 交易消息类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeMsgType type = 2;</code>
     */
    public Builder setType(TradeMsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易消息类型
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeMsgType type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int version_ = 0;
    /**
     * <pre>
     * 协议版本号
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.ProtoVersion version = 3;</code>
     */
    public int getVersionValue() {
      return version_;
    }
    /**
     * <pre>
     * 协议版本号
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.ProtoVersion version = 3;</code>
     */
    public Builder setVersionValue(int value) {
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议版本号
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.ProtoVersion version = 3;</code>
     */
    public ProtoVersion getVersion() {
      ProtoVersion result = ProtoVersion.valueOf(version_);
      return result == null ? ProtoVersion.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 协议版本号
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.ProtoVersion version = 3;</code>
     */
    public Builder setVersion(ProtoVersion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      version_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议版本号
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.ProtoVersion version = 3;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private TradeRetCode ret_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        TradeRetCode, TradeRetCode.Builder, TradeRetCodeOrBuilder> retBuilder_;
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public boolean hasRet() {
      return retBuilder_ != null || ret_ != null;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public TradeRetCode getRet() {
      if (retBuilder_ == null) {
        return ret_ == null ? TradeRetCode.getDefaultInstance() : ret_;
      } else {
        return retBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public Builder setRet(TradeRetCode value) {
      if (retBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ret_ = value;
        onChanged();
      } else {
        retBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public Builder setRet(
        TradeRetCode.Builder builderForValue) {
      if (retBuilder_ == null) {
        ret_ = builderForValue.build();
        onChanged();
      } else {
        retBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public Builder mergeRet(TradeRetCode value) {
      if (retBuilder_ == null) {
        if (ret_ != null) {
          ret_ =
            TradeRetCode.newBuilder(ret_).mergeFrom(value).buildPartial();
        } else {
          ret_ = value;
        }
        onChanged();
      } else {
        retBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public Builder clearRet() {
      if (retBuilder_ == null) {
        ret_ = null;
        onChanged();
      } else {
        ret_ = null;
        retBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public TradeRetCode.Builder getRetBuilder() {
      
      onChanged();
      return getRetFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    public TradeRetCodeOrBuilder getRetOrBuilder() {
      if (retBuilder_ != null) {
        return retBuilder_.getMessageOrBuilder();
      } else {
        return ret_ == null ?
            TradeRetCode.getDefaultInstance() : ret_;
      }
    }
    /**
     * <pre>
     * 错误信息
     * </pre>
     *
     * <code>optional .com.demo.model.proto.gateway.TradeRetCode ret = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        TradeRetCode, TradeRetCode.Builder, TradeRetCodeOrBuilder>
        getRetFieldBuilder() {
      if (retBuilder_ == null) {
        retBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            TradeRetCode, TradeRetCode.Builder, TradeRetCodeOrBuilder>(
                getRet(),
                getParentForChildren(),
                isClean());
        ret_ = null;
      }
      return retBuilder_;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 交易协议数据
     * </pre>
     *
     * <code>optional bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <pre>
     * 交易协议数据
     * </pre>
     *
     * <code>optional bytes data = 5;</code>
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 交易协议数据
     * </pre>
     *
     * <code>optional bytes data = 5;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private Object platform_ = "";
    /**
     * <pre>
     * 平台 IOS Android PC 
     * </pre>
     *
     * <code>optional string platform = 6;</code>
     */
    public String getPlatform() {
      Object ref = platform_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 平台 IOS Android PC 
     * </pre>
     *
     * <code>optional string platform = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 平台 IOS Android PC 
     * </pre>
     *
     * <code>optional string platform = 6;</code>
     */
    public Builder setPlatform(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 平台 IOS Android PC 
     * </pre>
     *
     * <code>optional string platform = 6;</code>
     */
    public Builder clearPlatform() {
      
      platform_ = getDefaultInstance().getPlatform();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 平台 IOS Android PC 
     * </pre>
     *
     * <code>optional string platform = 6;</code>
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platform_ = value;
      onChanged();
      return this;
    }

    private Object deviceId_ = "";
    /**
     * <pre>
     * 设备ID 
     * </pre>
     *
     * <code>optional string device_id = 7;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 设备ID 
     * </pre>
     *
     * <code>optional string device_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备ID 
     * </pre>
     *
     * <code>optional string device_id = 7;</code>
     */
    public Builder setDeviceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID 
     * </pre>
     *
     * <code>optional string device_id = 7;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID 
     * </pre>
     *
     * <code>optional string device_id = 7;</code>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.demo.model.proto.gateway.TradeMsgCarrier)
  }

  // @@protoc_insertion_point(class_scope:com.demo.model.proto.gateway.TradeMsgCarrier)
  private static final TradeMsgCarrier DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TradeMsgCarrier();
  }

  public static TradeMsgCarrier getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradeMsgCarrier>
      PARSER = new com.google.protobuf.AbstractParser<TradeMsgCarrier>() {
    public TradeMsgCarrier parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TradeMsgCarrier(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TradeMsgCarrier> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TradeMsgCarrier> getParserForType() {
    return PARSER;
  }

  public TradeMsgCarrier getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

