// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_common_type_def.proto

package com.demo.model.proto.trade.common;

/**
 * Protobuf enum {@code com.demo.model.proto.trade.common.ContractType}
 */
public enum ContractType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TRADE_QUOTE = 0;</code>
   */
  TRADE_QUOTE(0),
  /**
   * <code>QUOTE = 1;</code>
   */
  QUOTE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TRADE_QUOTE = 0;</code>
   */
  public static final int TRADE_QUOTE_VALUE = 0;
  /**
   * <code>QUOTE = 1;</code>
   */
  public static final int QUOTE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ContractType valueOf(int value) {
    return forNumber(value);
  }

  public static ContractType forNumber(int value) {
    switch (value) {
      case 0: return TRADE_QUOTE;
      case 1: return QUOTE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ContractType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ContractType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ContractType>() {
          public ContractType findValueByNumber(int number) {
            return ContractType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return TradeCommonTypeDef.getDescriptor()
        .getEnumTypes().get(13);
  }

  private static final ContractType[] VALUES = values();

  public static ContractType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ContractType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.demo.model.proto.trade.common.ContractType)
}

