// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_common_msg_def.proto

package com.demo.model.proto.trade.common;

public interface HeartRspMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.trade.common.HeartRspMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 占位符
   * </pre>
   *
   * <code>optional uint64 conn_id = 1;</code>
   */
  long getConnId();
}
