// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade_common_msg_def.proto

package com.demo.model.proto.trade.common;

public final class TradeCommonMsgDef {
  private TradeCommonMsgDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_HeartReqMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_HeartReqMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_HeartRspMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_HeartRspMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_VelocityReqMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_VelocityReqMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_VelocityRspMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_VelocityRspMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_TradingTimespin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_TradingTimespin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_InstrOrderLimit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_InstrOrderLimit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_InstrBaseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_InstrBaseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_ProductInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_ProductInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_InstrumentInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_InstrumentInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_StockInstr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_StockInstr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_FutureInstr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_FutureInstr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_OptionInstr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_OptionInstr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_ForexInstr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_ForexInstr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_model_proto_trade_common_InstrumentInfos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_model_proto_trade_common_InstrumentInfos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032trade_common_msg_def.proto\022!com.demo.m" +
      "odel.proto.trade.common\032\033trade_common_ty" +
      "pe_def.proto\"\036\n\013HeartReqMsg\022\017\n\007conn_id\030\001" +
      " \001(\004\"\036\n\013HeartRspMsg\022\017\n\007conn_id\030\001 \001(\004\"$\n\016" +
      "VelocityReqMsg\022\022\n\nstart_time\030\001 \001(\004\"J\n\016Ve" +
      "locityRspMsg\022\022\n\nstart_time\030\001 \001(\004\022\021\n\trecv" +
      "_time\030\002 \001(\004\022\021\n\tsend_time\030\003 \001(\004\"-\n\017Tradin" +
      "gTimespin\022\r\n\005start\030\001 \001(\r\022\013\n\003end\030\002 \001(\r\"?\n" +
      "\017InstrOrderLimit\022\025\n\rmax_order_qty\030\001 \001(\r\022" +
      "\025\n\rmin_order_qty\030\002 \001(\r\"\205\004\n\rInstrBaseInfo",
      "\022@\n\ninstr_type\030\001 \001(\0162,.com.demo.model.pr" +
      "oto.trade.common.InstrType\022A\n\010exchange\030\002" +
      " \001(\0162/.com.demo.model.proto.trade.common" +
      ".ExchangeType\022\021\n\tseries_id\030\003 \001(\t\022\022\n\ninst" +
      "r_code\030\004 \001(\t\022\025\n\rinternal_code\030\005 \001(\t\022\024\n\014c" +
      "ounter_code\030\006 \001(\t\022\026\n\016cn_simple_name\030\007 \001(" +
      "\t\022\026\n\016tc_simple_name\030\010 \001(\t\022\026\n\016en_simple_n" +
      "ame\030\t \001(\t\022\024\n\014cn_full_name\030\n \001(\t\022\024\n\014tc_fu" +
      "ll_name\030\013 \001(\t\022\024\n\014en_full_name\030\014 \001(\t\022H\n\017s" +
      "ettle_currency\030\r \001(\0162/.com.demo.model.pr",
      "oto.trade.common.CurrencyType\022G\n\016trade_c" +
      "urrency\030\016 \001(\0162/.com.demo.model.proto.tra" +
      "de.common.CurrencyType\"\321\003\n\013ProductInfo\022F" +
      "\n\rcategory_type\030\001 \001(\0162/.com.demo.model.p" +
      "roto.trade.common.CategoryType\022D\n\014produc" +
      "t_type\030\002 \001(\0162..com.demo.model.proto.trad" +
      "e.common.ProductType\022\014\n\004code\030\003 \001(\t\022\026\n\016cn" +
      "_simple_name\030\004 \001(\t\022\026\n\016tc_simple_name\030\005 \001" +
      "(\t\022\026\n\016en_simple_name\030\006 \001(\t\022\024\n\014cn_full_na" +
      "me\030\007 \001(\t\022\024\n\014tc_full_name\030\010 \001(\t\022\024\n\014en_ful",
      "l_name\030\t \001(\t\022\020\n\010timespin\030\n \001(\t\022G\n\013call_m" +
      "arket\030\013 \003(\01322.com.demo.model.proto.trade" +
      ".common.TradingTimespin\022A\n\005trade\030\014 \003(\01322" +
      ".com.demo.model.proto.trade.common.Tradi" +
      "ngTimespin\"\235\005\n\016InstrumentInfo\022>\n\004base\030\001 " +
      "\001(\01320.com.demo.model.proto.trade.common." +
      "InstrBaseInfo\022<\n\004proc\030\002 \001(\0132..com.demo.m" +
      "odel.proto.trade.common.ProductInfo\022\020\n\010l" +
      "ot_size\030\003 \001(\r\022\022\n\nprice_tick\030\004 \001(\004\022\022\n\nden" +
      "oinator\030\005 \001(\004\022\022\n\ntrade_able\030\006 \001(\010\022\021\n\tpre",
      "cision\030\007 \001(\r\022B\n\006status\030\010 \001(\01622.com.demo." +
      "model.proto.trade.common.InstrStatusType" +
      "\022\023\n\013create_date\030\t \001(\t\022\021\n\topen_date\030\n \001(\t" +
      "\022\024\n\014update_stamp\030\013 \001(\004\022\034\n\024price_tick_pre" +
      "cision\030\r \001(\r\022>\n\005stock\030\036 \001(\0132-.com.demo.m" +
      "odel.proto.trade.common.StockInstrH\000\022@\n\006" +
      "future\030\037 \001(\0132..com.demo.model.proto.trad" +
      "e.common.FutureInstrH\000\022=\n\003opt\030  \001(\0132..co" +
      "m.demo.model.proto.trade.common.OptionIn" +
      "strH\000\022>\n\005forex\030! \001(\0132-.com.demo.model.pr",
      "oto.trade.common.ForexInstrH\000B\013\n\tinstrDa" +
      "ta\"\035\n\nStockInstr\022\017\n\007reserve\030\001 \001(\r\"\273\004\n\013Fu" +
      "tureInstr\022J\n\020margin_rate_type\030\001 \001(\01620.co" +
      "m.demo.model.proto.trade.common.InstrRat" +
      "eType\022\023\n\013long_margin\030\002 \001(\004\022\024\n\014short_marg" +
      "in\030\003 \001(\004\022L\n\020market_order_qty\030\004 \001(\01322.com" +
      ".demo.model.proto.trade.common.InstrOrde" +
      "rLimit\022K\n\017limit_order_qty\030\005 \001(\01322.com.de" +
      "mo.model.proto.trade.common.InstrOrderLi" +
      "mit\022\033\n\023contract_multiplier\030\006 \001(\004\022\024\n\014deli",
      "ver_year\030\007 \001(\r\022\025\n\rdeliver_month\030\010 \001(\r\022\021\n" +
      "\tis_enable\030\t \001(\010\022\027\n\017is_master_instr\030\n \001(" +
      "\010\022\025\n\rrelated_instr\030\013 \001(\t\022\027\n\017last_trade_d" +
      "ate\030\014 \001(\t\022\023\n\013notify_date\030\r \001(\t\022\023\n\013expire" +
      "_date\030\016 \001(\t\022\024\n\014expire_month\030\017 \001(\r\022\032\n\022beg" +
      "in_deliver_date\030\020 \001(\t\022\030\n\020end_deliver_dat" +
      "e\030\021 \001(\t\"\362\004\n\013OptionInstr\022\027\n\017underlying_co" +
      "de\030\001 \001(\t\022L\n\023underlying_exchange\030\002 \001(\0162/." +
      "com.demo.model.proto.trade.common.Exchan" +
      "geType\022J\n\020margin_rate_type\030\003 \001(\01620.com.d",
      "emo.model.proto.trade.common.InstrRateTy" +
      "pe\022\023\n\013long_margin\030\004 \001(\004\022\024\n\014short_margin\030" +
      "\005 \001(\004\022L\n\020market_order_qty\030\006 \001(\01322.com.de" +
      "mo.model.proto.trade.common.InstrOrderLi" +
      "mit\022K\n\017limit_order_qty\030\007 \001(\01322.com.demo." +
      "model.proto.trade.common.InstrOrderLimit" +
      "\022\033\n\023contract_multiplier\030\010 \001(\004\022\024\n\014deliver" +
      "_year\030\t \001(\r\022\025\n\rdeliver_month\030\n \001(\r\022\021\n\tis" +
      "_enable\030\013 \001(\010\022\027\n\017last_trade_date\030\r \001(\t\022\023" +
      "\n\013notify_date\030\016 \001(\t\022\023\n\013expire_date\030\017 \001(\t",
      "\022\024\n\014expire_month\030\020 \001(\r\022\032\n\022begin_deliver_" +
      "date\030\021 \001(\t\022\030\n\020end_deliver_date\030\022 \001(\t\"\035\n\n" +
      "ForexInstr\022\017\n\007reserve\030\001 \001(\r\"S\n\017Instrumen" +
      "tInfos\022@\n\005infos\030\001 \003(\01321.com.demo.model.p" +
      "roto.trade.common.InstrumentInfoB\002P\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TradeCommonTypeDef.getDescriptor(),
        }, assigner);
    internal_static_com_demo_model_proto_trade_common_HeartReqMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_model_proto_trade_common_HeartReqMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_HeartReqMsg_descriptor,
        new String[] { "ConnId", });
    internal_static_com_demo_model_proto_trade_common_HeartRspMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_model_proto_trade_common_HeartRspMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_HeartRspMsg_descriptor,
        new String[] { "ConnId", });
    internal_static_com_demo_model_proto_trade_common_VelocityReqMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_demo_model_proto_trade_common_VelocityReqMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_VelocityReqMsg_descriptor,
        new String[] { "StartTime", });
    internal_static_com_demo_model_proto_trade_common_VelocityRspMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_demo_model_proto_trade_common_VelocityRspMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_VelocityRspMsg_descriptor,
        new String[] { "StartTime", "RecvTime", "SendTime", });
    internal_static_com_demo_model_proto_trade_common_TradingTimespin_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_demo_model_proto_trade_common_TradingTimespin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_TradingTimespin_descriptor,
        new String[] { "Start", "End", });
    internal_static_com_demo_model_proto_trade_common_InstrOrderLimit_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_demo_model_proto_trade_common_InstrOrderLimit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_InstrOrderLimit_descriptor,
        new String[] { "MaxOrderQty", "MinOrderQty", });
    internal_static_com_demo_model_proto_trade_common_InstrBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_demo_model_proto_trade_common_InstrBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_InstrBaseInfo_descriptor,
        new String[] { "InstrType", "Exchange", "SeriesId", "InstrCode", "InternalCode", "CounterCode", "CnSimpleName", "TcSimpleName", "EnSimpleName", "CnFullName", "TcFullName", "EnFullName", "SettleCurrency", "TradeCurrency", });
    internal_static_com_demo_model_proto_trade_common_ProductInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_demo_model_proto_trade_common_ProductInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_ProductInfo_descriptor,
        new String[] { "CategoryType", "ProductType", "Code", "CnSimpleName", "TcSimpleName", "EnSimpleName", "CnFullName", "TcFullName", "EnFullName", "Timespin", "CallMarket", "Trade", });
    internal_static_com_demo_model_proto_trade_common_InstrumentInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_demo_model_proto_trade_common_InstrumentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_InstrumentInfo_descriptor,
        new String[] { "Base", "Proc", "LotSize", "PriceTick", "Denoinator", "TradeAble", "Precision", "Status", "CreateDate", "OpenDate", "UpdateStamp", "PriceTickPrecision", "Stock", "Future", "Opt", "Forex", "InstrData", });
    internal_static_com_demo_model_proto_trade_common_StockInstr_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_demo_model_proto_trade_common_StockInstr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_StockInstr_descriptor,
        new String[] { "Reserve", });
    internal_static_com_demo_model_proto_trade_common_FutureInstr_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_demo_model_proto_trade_common_FutureInstr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_FutureInstr_descriptor,
        new String[] { "MarginRateType", "LongMargin", "ShortMargin", "MarketOrderQty", "LimitOrderQty", "ContractMultiplier", "DeliverYear", "DeliverMonth", "IsEnable", "IsMasterInstr", "RelatedInstr", "LastTradeDate", "NotifyDate", "ExpireDate", "ExpireMonth", "BeginDeliverDate", "EndDeliverDate", });
    internal_static_com_demo_model_proto_trade_common_OptionInstr_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_demo_model_proto_trade_common_OptionInstr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_OptionInstr_descriptor,
        new String[] { "UnderlyingCode", "UnderlyingExchange", "MarginRateType", "LongMargin", "ShortMargin", "MarketOrderQty", "LimitOrderQty", "ContractMultiplier", "DeliverYear", "DeliverMonth", "IsEnable", "LastTradeDate", "NotifyDate", "ExpireDate", "ExpireMonth", "BeginDeliverDate", "EndDeliverDate", });
    internal_static_com_demo_model_proto_trade_common_ForexInstr_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_demo_model_proto_trade_common_ForexInstr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_ForexInstr_descriptor,
        new String[] { "Reserve", });
    internal_static_com_demo_model_proto_trade_common_InstrumentInfos_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_demo_model_proto_trade_common_InstrumentInfos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_model_proto_trade_common_InstrumentInfos_descriptor,
        new String[] { "Infos", });
    TradeCommonTypeDef.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
