// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_msg_def.proto

package com.demo.model.proto.common;

public interface ForexInstrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.common.ForexInstr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 占位符
   * </pre>
   *
   * <code>optional uint32 reserve = 1;</code>
   */
  int getReserve();
}
