// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_msg_def.proto

package com.demo.model.proto.common;

public interface ProductInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.model.proto.common.ProductInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 品种大类
   * </pre>
   *
   * <code>optional .com.demo.model.proto.common.CategoryType category_type = 1;</code>
   */
  int getCategoryTypeValue();
  /**
   * <pre>
   * 品种大类
   * </pre>
   *
   * <code>optional .com.demo.model.proto.common.CategoryType category_type = 1;</code>
   */
  CategoryType getCategoryType();

  /**
   * <pre>
   * 品种类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.common.ProductType product_type = 2;</code>
   */
  int getProductTypeValue();
  /**
   * <pre>
   * 品种类型
   * </pre>
   *
   * <code>optional .com.demo.model.proto.common.ProductType product_type = 2;</code>
   */
  ProductType getProductType();

  /**
   * <pre>
   * 品种代码
   * </pre>
   *
   * <code>optional string code = 3;</code>
   */
  String getCode();
  /**
   * <pre>
   * 品种代码
   * </pre>
   *
   * <code>optional string code = 3;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * 品种简体简称
   * </pre>
   *
   * <code>optional string cn_simple_name = 4;</code>
   */
  String getCnSimpleName();
  /**
   * <pre>
   * 品种简体简称
   * </pre>
   *
   * <code>optional string cn_simple_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getCnSimpleNameBytes();

  /**
   * <pre>
   * 品种繁体简称
   * </pre>
   *
   * <code>optional string tc_simple_name = 5;</code>
   */
  String getTcSimpleName();
  /**
   * <pre>
   * 品种繁体简称
   * </pre>
   *
   * <code>optional string tc_simple_name = 5;</code>
   */
  com.google.protobuf.ByteString
      getTcSimpleNameBytes();

  /**
   * <pre>
   * 品种英文简称
   * </pre>
   *
   * <code>optional string en_simple_name = 6;</code>
   */
  String getEnSimpleName();
  /**
   * <pre>
   * 品种英文简称
   * </pre>
   *
   * <code>optional string en_simple_name = 6;</code>
   */
  com.google.protobuf.ByteString
      getEnSimpleNameBytes();

  /**
   * <pre>
   * 品种简体全称
   * </pre>
   *
   * <code>optional string cn_full_name = 7;</code>
   */
  String getCnFullName();
  /**
   * <pre>
   * 品种简体全称
   * </pre>
   *
   * <code>optional string cn_full_name = 7;</code>
   */
  com.google.protobuf.ByteString
      getCnFullNameBytes();

  /**
   * <pre>
   * 品种繁体全称 
   * </pre>
   *
   * <code>optional string tc_full_name = 8;</code>
   */
  String getTcFullName();
  /**
   * <pre>
   * 品种繁体全称 
   * </pre>
   *
   * <code>optional string tc_full_name = 8;</code>
   */
  com.google.protobuf.ByteString
      getTcFullNameBytes();

  /**
   * <pre>
   * 品种英文全称
   * </pre>
   *
   * <code>optional string en_full_name = 9;</code>
   */
  String getEnFullName();
  /**
   * <pre>
   * 品种英文全称
   * </pre>
   *
   * <code>optional string en_full_name = 9;</code>
   */
  com.google.protobuf.ByteString
      getEnFullNameBytes();

  /**
   * <pre>
   * 时间片
   * </pre>
   *
   * <code>optional string timespin = 10;</code>
   */
  String getTimespin();
  /**
   * <pre>
   * 时间片
   * </pre>
   *
   * <code>optional string timespin = 10;</code>
   */
  com.google.protobuf.ByteString
      getTimespinBytes();

  /**
   * <pre>
   * 集合竞价时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin call_market = 11;</code>
   */
  java.util.List<TradingTimespin>
      getCallMarketList();
  /**
   * <pre>
   * 集合竞价时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin call_market = 11;</code>
   */
  TradingTimespin getCallMarket(int index);
  /**
   * <pre>
   * 集合竞价时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin call_market = 11;</code>
   */
  int getCallMarketCount();
  /**
   * <pre>
   * 集合竞价时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin call_market = 11;</code>
   */
  java.util.List<? extends TradingTimespinOrBuilder>
      getCallMarketOrBuilderList();
  /**
   * <pre>
   * 集合竞价时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin call_market = 11;</code>
   */
  TradingTimespinOrBuilder getCallMarketOrBuilder(
      int index);

  /**
   * <pre>
   * 交易时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin trade = 12;</code>
   */
  java.util.List<TradingTimespin>
      getTradeList();
  /**
   * <pre>
   * 交易时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin trade = 12;</code>
   */
  TradingTimespin getTrade(int index);
  /**
   * <pre>
   * 交易时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin trade = 12;</code>
   */
  int getTradeCount();
  /**
   * <pre>
   * 交易时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin trade = 12;</code>
   */
  java.util.List<? extends TradingTimespinOrBuilder>
      getTradeOrBuilderList();
  /**
   * <pre>
   * 交易时间片
   * </pre>
   *
   * <code>repeated .com.demo.model.proto.common.TradingTimespin trade = 12;</code>
   */
  TradingTimespinOrBuilder getTradeOrBuilder(
      int index);
}
